import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { m, min } from '../../../packages/typescriptcss/src'
import './tcss.css'

const geistSans = Geist({
        variable: '--font-geist-sans',
        subsets: ['latin'],
})

const geistMono = Geist_Mono({
        variable: '--font-geist-mono',
        subsets: ['latin'],
})

export const metadata: Metadata = {
        title: 'Create Next App',
        description: 'Generated by create next app',
}

export default function RootLayout({
        children,
}: Readonly<{
        children: React.ReactNode
}>) {
        return (
                <html lang="en" style={m[0].p[0].h.full()} className={`${geistSans.variable} ${geistMono.variable}`}>
                        <body style={m[0].p[0].min.h.full.flex.col()}>{children}</body>
                </html>
        )
}
