import { borderRule, borderSideRule, colorRule, columnRule, columnsRule, controls, darkRule, defaultFilterRule, divideRule, filterRule, flexRule, group, lengthRule, mediaRule, numericRule, opacityRule, outlineRule, positionRule, propertyRule, roundedRule, rowRule, rowsRule, scaleRule, scopedRule, sizePropsRule, sizeRule, spacingRule, splitRule, textRule, transformRule, translateRule, utility, values, variantRule } from './utils.ts'
import type { Chain, RuntimeStyle, Utility } from './types.ts'
controls('active', 'after', 'aria', 'ariaChecked', 'ariaDisabled', 'ariaExpanded', 'ariaSelected', 'atLg', 'atMd', 'atSm', 'autofill', 'before', 'bg', 'border', 'checked', 'child', 'contrastLess', 'contrastMore', 'css', 'dark', 'data', 'dataActive', 'descendant', 'disabled', 'empty', 'enabled', 'even', 'file', 'fill', 'first', 'firstLetter', 'firstLine', 'firstOfType', 'focus', 'focusVisible', 'focusWithin', 'forcedColors', 'group', 'groupFocus', 'groupHover', 'has', 'hover', 'indeterminate', 'invalid', 'landscape', 'last', 'lastOfType', 'lg', 'light', 'ltr', 'maxMd', 'maxSm', 'md', 'motionReduce', 'motionSafe', 'odd', 'only', 'onlyOfType', 'optional', 'peer', 'peerFocus', 'peerHover', 'placeholder', 'placeholderShown', 'pointerCoarse', 'pointerFine', 'portrait', 'prefersDark', 'print', 'readOnly', 'required', 'rtl', 'selection', 'shadow', 'sm', 'stroke', 'supports', 'target', 'text', 'valid', 'visited', 'xl', 'xl2')
const contentValues = { baseline: 'baseline', center: 'center', end: 'flex-end', 'flex-end': 'flex-end', 'flex-start': 'flex-start', normal: 'normal', 'safe center': 'safe center', 'safe end': 'safe end', 'safe flex-end': 'safe flex-end', 'space-around': 'space-around', 'space-be_een': 'space-between', 'space-between': 'space-between', 'space-evenly': 'space-evenly', start: 'flex-start', stretch: 'stretch' }
const itemValues = { baseline: 'baseline', center: 'center', end: 'flex-end', 'flex-end': 'flex-end', 'flex-start': 'flex-start', normal: 'normal', 'last baseline': 'last baseline', 'safe center': 'safe center', 'safe end': 'safe end', 'safe flex-end': 'safe flex-end', start: 'flex-start', stretch: 'stretch' }
const boxValues = { auto: 'auto', avoid: 'avoid', all: 'all', 'avoid-page': 'avoid-page', 'avoid-column': 'avoid-column', page: 'page', left: 'left', right: 'right', column: 'column' }
const blendValues = { normal: 'normal', multiply: 'multiply', screen: 'screen', overlay: 'overlay', darken: 'darken', lighten: 'lighten', 'color-dodge': 'color-dodge', 'color-burn': 'color-burn', 'hard-light': 'hard-light', 'soft-light': 'soft-light', difference: 'difference', exclusion: 'exclusion', hue: 'hue', saturation: 'saturation', color: 'color', luminosity: 'luminosity', 'plus-darker': 'plus-darker', 'plus-lighter': 'plus-lighter' }
const positionValues = { bottom: 'bottom', 'bottom left': 'bottom left', 'bottom right': 'bottom right', center: 'center', left: 'left', right: 'right', top: 'top', 'top left': 'top left', 'top right': 'top right' }
const repeatValues = { repeat: 'repeat', 'repeat-x': 'repeat-x', 'repeat-y': 'repeat-y', space: 'space', round: 'round', 'no-repeat': 'no-repeat' }
const cursorValues = { alias: 'alias', auto: 'auto', cell: 'cell', copy: 'copy', crosshair: 'crosshair', default: 'default', grab: 'grab', grabbing: 'grabbing', help: 'help', move: 'move', none: 'none', pointer: 'pointer', progress: 'progress', text: 'text', wait: 'wait' }
group('auto', { cols: scopedRule('autoCols', propertyRule('gridAutoColumns')), rows: scopedRule('autoRows', propertyRule('gridAutoRows')) })
group('autoCols', { ...values('gridAutoColumns', { auto: 'auto', 'min-content': 'min-content', 'max-content': 'max-content', 'minmax(0, 1fr)': 'minmax(0, 1fr)' }) })
group('autoRows', { ...values('gridAutoRows', { auto: 'auto', 'min-content': 'min-content', 'max-content': 'max-content', 'minmax(0, 1fr)': 'minmax(0, 1fr)' }) })
group('bg', { ...values('backgroundAttachment', { fixed: 'fixed', local: 'local', scroll: 'scroll' }), ...values('backgroundSize', { auto: 'auto', cover: 'cover', contain: 'contain' }), blend: scopedRule('bgBlend', {}), clip: scopedRule('bgClip', {}), origin: scopedRule('bgOrigin', {}), position: scopedRule('bgPosition', propertyRule('backgroundPosition')), repeat: scopedRule('bgRepeat', {}), size: scopedRule('bgSize', scaleRule('backgroundSize')) })
group('bgBlend', values('backgroundBlendMode', blendValues))
group('bgClip', values('backgroundClip', { 'border-box': 'border-box', 'padding-box': 'padding-box', 'content-box': 'content-box', text: 'text' }))
group('bgOrigin', values('backgroundOrigin', { 'border-box': 'border-box', 'padding-box': 'padding-box', 'content-box': 'content-box' }))
group('bgPosition', values('backgroundPosition', positionValues))
group('bgRepeat', values('backgroundRepeat', repeatValues))
group('border', { ...values('borderStyle', { solid: 'solid', dashed: 'dashed', dotted: 'dotted', double: 'double', hidden: 'hidden', none: 'none' }), b: borderSideRule('borderBottom'), be: borderSideRule('borderBlockEnd'), bs: borderSideRule('borderBlockStart'), collapse: { borderCollapse: 'collapse' }, e: borderSideRule('borderInlineEnd'), l: borderSideRule('borderLeft'), r: borderSideRule('borderRight'), s: borderSideRule('borderInlineStart'), separate: { borderCollapse: 'separate' }, t: borderSideRule('borderTop'), x: borderSideRule('borderLeft', 'borderRight'), y: borderSideRule('borderBottom', 'borderTop') })
group('box', { decoration: scopedRule('boxDecoration', {}), ...values('boxSizing', { 'border-box': 'border-box', 'content-box': 'content-box' }) })
group('boxDecoration', values('boxDecorationBreak', { clone: 'clone', slice: 'slice' }))
group('break', { after: scopedRule('breakAfter', {}), before: scopedRule('breakBefore', {}), inside: scopedRule('breakInside', {}), normal: { overflowWrap: 'normal', wordBreak: 'normal' }, 'break-all': { wordBreak: 'break-all' }, 'keep-all': { wordBreak: 'keep-all' } })
group('breakAfter', values('breakAfter', boxValues))
group('breakBefore', values('breakBefore', boxValues))
group('breakInside', values('breakInside', boxValues))
group('caption', values('captionSide', { top: 'top', bottom: 'bottom' }))
group('clear', values('clear', { left: 'left', right: 'right', both: 'both', 'inline-start': 'inline-start', 'inline-end': 'inline-end', none: 'none' }))
group('col', { auto: { gridColumn: 'auto' }, end: scopedRule('colEnd', propertyRule('gridColumnEnd')), full: { gridColumn: '1 / -1' }, span: numericRule((key) => ({ gridColumn: `span ${key} / span ${key}` })), start: scopedRule('colStart', propertyRule('gridColumnStart')) })
group('cols', { none: { gridTemplateColumns: 'none' }, subgrid: { gridTemplateColumns: 'subgrid' } })
group('content', { ...values('alignContent', contentValues), none: { content: 'none' } })
group('cursor', { ...values('cursor', cursorValues), all: scopedRule('cursorAll', {}), col: scopedRule('cursorCol', {}), context: scopedRule('cursorContext', {}), e: scopedRule('cursorE', {}), ew: scopedRule('cursorEw', {}), n: scopedRule('cursorN', {}), ne: scopedRule('cursorNe', {}), nesw: scopedRule('cursorNesw', {}), no: scopedRule('cursorNo', {}), not: scopedRule('cursorNot', {}), ns: scopedRule('cursorNs', {}), nw: scopedRule('cursorNw', {}), nwse: scopedRule('cursorNwse', {}), row: scopedRule('cursorRow', {}), s: scopedRule('cursorS', {}), se: scopedRule('cursorSe', {}), sw: scopedRule('cursorSw', {}), vertical: scopedRule('cursorVertical', {}), w: scopedRule('cursorW', {}), zoom: scopedRule('cursorZoom', {}) })
group('cursorAll', { scroll: { cursor: 'all-scroll' } })
group('cursorCol', { resize: { cursor: 'col-resize' } })
group('cursorContext', { menu: { cursor: 'context-menu' } })
group('cursorE', { resize: { cursor: 'e-resize' } })
group('cursorEw', { resize: { cursor: 'ew-resize' } })
group('cursorN', { resize: { cursor: 'n-resize' } })
group('cursorNe', { resize: { cursor: 'ne-resize' } })
group('cursorNesw', { resize: { cursor: 'nesw-resize' } })
group('cursorNo', { drop: { cursor: 'no-drop' } })
group('cursorNot', { allowed: { cursor: 'not-allowed' } })
group('cursorNs', { resize: { cursor: 'ns-resize' } })
group('cursorNw', { resize: { cursor: 'nw-resize' } })
group('cursorNwse', { resize: { cursor: 'nwse-resize' } })
group('cursorRow', { resize: { cursor: 'row-resize' } })
group('cursorS', { resize: { cursor: 's-resize' } })
group('cursorSe', { resize: { cursor: 'se-resize' } })
group('cursorSw', { resize: { cursor: 'sw-resize' } })
group('cursorVertical', { text: { cursor: 'vertical-text' } })
group('cursorW', { resize: { cursor: 'w-resize' } })
group('cursorZoom', { in: { cursor: 'zoom-in' }, out: { cursor: 'zoom-out' } })
group('decoration', { ...values('textDecorationStyle', { solid: 'solid', double: 'double', dotted: 'dotted', dashed: 'dashed', wavy: 'wavy' }), auto: { textDecorationThickness: 'auto' }, 'from-font': { textDecorationThickness: 'from-font' } })
group('display', values('display', { inline: 'inline', block: 'block', 'inline-block': 'inline-block', 'flow-root': 'flow-root', flex: 'flex', 'inline-flex': 'inline-flex', grid: 'grid', 'inline-grid': 'inline-grid', contents: 'contents', table: 'table', 'inline-table': 'inline-table', 'table-caption': 'table-caption', 'table-cell': 'table-cell', 'table-column': 'table-column', 'table-column-group': 'table-column-group', 'table-footer-group': 'table-footer-group', 'table-header-group': 'table-header-group', 'table-row-group': 'table-row-group', 'table-row': 'table-row', 'list-item': 'list-item', none: 'none' }))
group('divide', { ...values('borderStyle', { solid: 'solid', dashed: 'dashed', dotted: 'dotted', double: 'double', hidden: 'hidden', none: 'none' }), x: divideRule('borderLeftWidth', 'borderRightWidth'), y: divideRule('borderTopWidth', 'borderBottomWidth') })
group('field', { sizing: scopedRule('fieldSizing', {}) })
group('fieldSizing', values('fieldSizing', { fixed: 'fixed', content: 'content' }))
group('filter', { none: { filter: 'none' } })
group('flex', { ...values('flexDirection', { col: 'column', column: 'column', row: 'row', 'row-reverse': 'row-reverse', 'column-reverse': 'column-reverse' }), ...values('flexWrap', { nowrap: 'nowrap', wrap: 'wrap', 'wrap-reverse': 'wrap-reverse' }), auto: { flex: '1 1 auto' }, none: { flex: 'none' }, '0 auto': { flex: '0 auto' } })
group('flow', values('gridAutoFlow', { row: 'row', column: 'column', col: 'column', dense: 'dense', 'row dense': 'row dense', 'column dense': 'column dense' }))
group('font', { ...values('fontWeight', { bold: 700, medium: 500, normal: 400, semibold: 600, '100': 100, '200': 200, '300': 300, '400': 400, '500': 500, '600': 600, '700': 700, '800': 800, '900': 900 }), features: scopedRule('fontFeatures', propertyRule('fontFeatureSettings')), mono: { fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace' }, sans: { fontFamily: 'Arial, Helvetica, sans-serif' }, serif: { fontFamily: 'Georgia, Cambria, Times New Roman, Times, serif' }, stretch: scopedRule('fontStretch', propertyRule('fontStretch')) })
group('fontStretch', values('fontStretch', { 'ultra-condensed': 'ultra-condensed', 'extra-condensed': 'extra-condensed', condensed: 'condensed', 'semi-condensed': 'semi-condensed', normal: 'normal', 'semi-expanded': 'semi-expanded', expanded: 'expanded', 'extra-expanded': 'extra-expanded', 'ultra-expanded': 'ultra-expanded' }))
group('gap', { x: scaleRule('columnGap'), y: scaleRule('rowGap') })
group('grid', { cols: scopedRule('cols', columnsRule), flow: scopedRule('flow', {}), rows: scopedRule('rows', rowsRule) })
group('hyphens', values('hyphens', { none: 'none', manual: 'manual', auto: 'auto' }))
group('inline', { block: { display: 'inline-block' }, flex: { display: 'inline-flex' } })
group('inset', { x: positionRule('left', 'right'), y: positionRule('bottom', 'top') })
group('isolation', values('isolation', { isolate: 'isolate', auto: 'auto' }))
group('items', values('alignItems', itemValues))
group('justify', { ...values('justifyContent', contentValues), items: scopedRule('justifyItems', {}), self: scopedRule('justifySelf', {}) })
group('justifyItems', values('justifyItems', { center: 'center', end: 'end', normal: 'normal', 'safe center': 'safe center', 'safe end': 'safe end', start: 'start', stretch: 'stretch' }))
group('justifySelf', values('justifySelf', { auto: 'auto', center: 'center', end: 'end', 'safe center': 'safe center', 'safe end': 'safe end', start: 'start', stretch: 'stretch' }))
// prettier-ignore
group('line', { clamp: scopedRule('lineClamp', numericRule((key) => ({ overflow: 'hidden', display: '-webkit-box', WebkitBoxOrient: 'vertical', WebkitLineClamp: Number(key) }))) })
group('lineClamp', { none: { overflow: 'visible', display: 'block', WebkitBoxOrient: 'horizontal', WebkitLineClamp: 'none' } })
group('list', { ...values('listStylePosition', { inside: 'inside', outside: 'outside' }), ...values('listStyleType', { disc: 'disc', decimal: 'decimal', none: 'none' }), image: scopedRule('listImage', propertyRule('listStyleImage')) })
group('listImage', { none: { listStyleImage: 'none' } })
group('mask', { add: { maskComposite: 'add' }, alpha: { maskMode: 'alpha' }, auto: { maskSize: 'auto' }, clip: scopedRule('maskClip', {}), contain: { maskSize: 'contain' }, cover: { maskSize: 'cover' }, exclude: { maskComposite: 'exclude' }, intersect: { maskComposite: 'intersect' }, luminance: { maskMode: 'luminance' }, 'match-source': { maskMode: 'match-source' }, none: { maskImage: 'none' }, origin: scopedRule('maskOrigin', {}), position: scopedRule('maskPosition', propertyRule('maskPosition')), radial: scopedRule('maskRadial', scaleRule('maskImage')), repeat: scopedRule('maskRepeat', {}), size: scopedRule('maskSize', scaleRule('maskSize')), subtract: { maskComposite: 'subtract' } })
group('maskClip', values('maskClip', { 'border-box': 'border-box', 'padding-box': 'padding-box', 'content-box': 'content-box', 'fill-box': 'fill-box', 'stroke-box': 'stroke-box', 'view-box': 'view-box', 'no-clip': 'no-clip' }))
group('maskOrigin', values('maskOrigin', { 'border-box': 'border-box', 'padding-box': 'padding-box', 'content-box': 'content-box', 'fill-box': 'fill-box', 'stroke-box': 'stroke-box', 'view-box': 'view-box' }))
group('maskPosition', values('maskPosition', positionValues))
group('maskRepeat', values('maskRepeat', repeatValues))
group('max', { h: lengthRule('maxHeight'), size: scopedRule('maxSize', sizePropsRule('maxHeight', 'maxWidth')), w: lengthRule('maxWidth') })
group('min', { h: lengthRule('minHeight'), size: scopedRule('minSize', sizePropsRule('minHeight', 'minWidth')), w: lengthRule('minWidth') })
group('mix', { blend: scopedRule('mixBlend', {}) })
group('mixBlend', values('mixBlendMode', blendValues))
group('not', { sr: scopedRule('notSr', {}) })
group('notSr', { only: { position: 'static', width: 'auto', height: 'auto', padding: '0', margin: '0', overflow: 'visible', clip: 'auto', whiteSpace: 'normal' } })
group('object', { ...values('objectFit', { contain: 'contain', cover: 'cover', fill: 'fill', none: 'none', 'scale-down': 'scale-down' }), ...values('objectPosition', positionValues) })
group('origin', { center: { transformOrigin: 'center' }, top: scopedRule('originTop', { transformOrigin: 'top' }), right: { transformOrigin: 'right' }, bottom: scopedRule('originBottom', { transformOrigin: 'bottom' }), left: { transformOrigin: 'left' } })
group('originTop', { right: { transformOrigin: 'top right' }, left: { transformOrigin: 'top left' } })
group('originBottom', { right: { transformOrigin: 'bottom right' }, left: { transformOrigin: 'bottom left' } })
// prettier-ignore
group('outline', { ...values('outlineStyle', { solid: 'solid', dashed: 'dashed', dotted: 'dotted', double: 'double', none: 'none', hidden: 'hidden' }), offset: scopedRule('outlineOffset', propertyRule('outlineOffset', (key) => `${Number(key)}px`)) })
group('overflow', { ...values('overflow', { auto: 'auto', hidden: 'hidden', clip: 'clip', visible: 'visible', scroll: 'scroll' }), x: scopedRule('overflowX', {}), y: scopedRule('overflowY', {}) })
group('overflowX', values('overflowX', { auto: 'auto', hidden: 'hidden', clip: 'clip', visible: 'visible', scroll: 'scroll' }))
group('overflowY', values('overflowY', { auto: 'auto', hidden: 'hidden', clip: 'clip', visible: 'visible', scroll: 'scroll' }))
group('overscroll', { ...values('overscrollBehavior', { auto: 'auto', contain: 'contain', none: 'none' }), x: scopedRule('overscrollX', {}), y: scopedRule('overscrollY', {}) })
group('overscrollX', values('overscrollBehaviorX', { auto: 'auto', contain: 'contain', none: 'none' }))
group('overscrollY', values('overscrollBehaviorY', { auto: 'auto', contain: 'contain', none: 'none' }))
group('perspective', { ...values('perspective', { dramatic: '100px', near: '300px', normal: '500px', midrange: '800px', distant: '1200px', none: 'none' }), origin: scopedRule('perspectiveOrigin', {}) })
group('perspectiveOrigin', { center: { perspectiveOrigin: 'center' }, top: scopedRule('perspectiveTop', { perspectiveOrigin: 'top' }), right: { perspectiveOrigin: 'right' }, bottom: scopedRule('perspectiveBottom', { perspectiveOrigin: 'bottom' }), left: { perspectiveOrigin: 'left' } })
group('perspectiveTop', { right: { perspectiveOrigin: 'top right' }, left: { perspectiveOrigin: 'top left' } })
group('perspectiveBottom', { right: { perspectiveOrigin: 'bottom right' }, left: { perspectiveOrigin: 'bottom left' } })
group('place', { content: scopedRule('placeContent', {}), items: scopedRule('placeItems', {}), self: scopedRule('placeSelf', {}) })
group('placeContent', values('placeContent', contentValues))
group('placeItems', values('placeItems', { baseline: 'baseline', center: 'center', end: 'end', 'safe center': 'safe center', 'safe end': 'safe end', start: 'start', stretch: 'stretch' }))
group('placeSelf', values('placeSelf', { auto: 'auto', center: 'center', end: 'end', 'safe center': 'safe center', 'safe end': 'safe end', start: 'start', stretch: 'stretch' }))
group('pointer', { events: scopedRule('pointerEvents', {}) })
group('pointerEvents', values('pointerEvents', { auto: 'auto', none: 'none' }))
group('position', values('position', { static: 'static', fixed: 'fixed', absolute: 'absolute', relative: 'relative', sticky: 'sticky' }))
group('resize', values('resize', { none: 'none', y: 'vertical', x: 'horizontal' }))
group('rounded', { b: roundedRule('borderBottomLeftRadius', 'borderBottomRightRadius'), bl: roundedRule('borderBottomLeftRadius'), br: roundedRule('borderBottomRightRadius'), e: roundedRule('borderStartEndRadius', 'borderEndEndRadius'), ee: roundedRule('borderEndEndRadius'), es: roundedRule('borderEndStartRadius'), l: roundedRule('borderBottomLeftRadius', 'borderTopLeftRadius'), r: roundedRule('borderBottomRightRadius', 'borderTopRightRadius'), s: roundedRule('borderStartStartRadius', 'borderEndStartRadius'), se: roundedRule('borderStartEndRadius'), ss: roundedRule('borderStartStartRadius'), t: roundedRule('borderTopLeftRadius', 'borderTopRightRadius'), tl: roundedRule('borderTopLeftRadius'), tr: roundedRule('borderTopRightRadius') })
group('row', { auto: { gridRow: 'auto' }, end: scopedRule('rowEnd', propertyRule('gridRowEnd')), full: { gridRow: '1 / -1' }, span: numericRule((key) => ({ gridRow: `span ${key} / span ${key}` })), start: scopedRule('rowStart', propertyRule('gridRowStart')) })
group('rows', { none: { gridTemplateRows: 'none' }, subgrid: { gridTemplateRows: 'subgrid' } })
group('scheme', { normal: { colorScheme: 'normal' }, dark: { colorScheme: 'dark' }, light: scopedRule('schemeLight', { colorScheme: 'light' }), only: scopedRule('schemeOnly', {}) })
group('schemeLight', { dark: { colorScheme: 'light dark' } })
group('schemeOnly', { dark: { colorScheme: 'only dark' }, light: { colorScheme: 'only light' } })
group('scroll', values('scrollBehavior', { auto: 'auto', smooth: 'smooth' }))
group('scrollbar', { auto: { scrollbarWidth: 'auto' }, none: { scrollbarWidth: 'none' }, thin: { scrollbarWidth: 'thin' }, gutter: scopedRule('scrollbarGutter', {}), thumb: scopedRule('scrollbarThumb', colorRule('scrollbarColor')), track: scopedRule('scrollbarTrack', colorRule('scrollbarColor')) })
group('scrollbarGutter', { auto: { scrollbarGutter: 'auto' }, stable: { scrollbarGutter: 'stable' }, both: { scrollbarGutter: 'stable both-edges' } })
group('select', values('userSelect', { none: 'none', text: 'text', all: 'all', auto: 'auto' }))
group('self', values('alignSelf', itemValues))
group('shadow', { none: { boxShadow: 'none' }, lg: { boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1)' } })
group('size', { auto: { width: 'auto', height: 'auto' }, px: { width: '1px', height: '1px' } })
group('snap', { align: scopedRule('snapAlign', {}), always: { scrollSnapStop: 'always' }, center: { scrollSnapAlign: 'center' }, end: { scrollSnapAlign: 'end' }, none: { scrollSnapType: 'none' }, normal: { scrollSnapStop: 'normal' }, start: { scrollSnapAlign: 'start' } })
group('snapAlign', { none: { scrollSnapAlign: 'none' } })
group('sr', { only: { position: 'absolute', width: '1px', height: '1px', padding: '0', margin: '-1px', overflow: 'hidden', clip: 'rect(0, 0, 0, 0)', clipPath: 'inset(50%)', whiteSpace: 'nowrap', borderWidth: '0' } })
group('table', values('tableLayout', { auto: 'auto', fixed: 'fixed' }))
group('text', { ...values('textAlign', { center: 'center', left: 'left', right: 'right', justify: 'justify', start: 'start', end: 'end' }), ...values('textWrap', { wrap: 'wrap', nowrap: 'nowrap', balance: 'balance', pretty: 'pretty' }), base: { fontSize: '16px', lineHeight: '24px' }, clip: { textOverflow: 'clip' }, ellipsis: { textOverflow: 'ellipsis' }, lg: { fontSize: '18px', lineHeight: '28px' }, shadow: scopedRule('textShadow', propertyRule('textShadow')), sm: { fontSize: '14px', lineHeight: '20px' }, xl: { fontSize: '20px', lineHeight: '28px' }, xs: { fontSize: '12px', lineHeight: '16px' } })
group('touch', { ...values('touchAction', { auto: 'auto', none: 'none', manipulation: 'manipulation' }), pan: scopedRule('touchPan', {}), pinch: scopedRule('touchPinch', {}) })
group('touchPan', values('touchAction', { x: 'pan-x', left: 'pan-left', right: 'pan-right', y: 'pan-y', up: 'pan-up', down: 'pan-down' }))
group('touchPinch', { zoom: { touchAction: 'pinch-zoom' } })
group('tracking', { ...values('letterSpacing', { tighter: '-0.05em', tight: '-0.025em', normal: '0em', wide: '0.025em', wider: '0.05em', widest: '0.1em' }) })
group('transform', { none: { transform: 'none' }, '3d': { transformStyle: 'preserve-3d' }, flat: { transformStyle: 'flat' } })
group('transition', { ...values('transitionProperty', { all: 'all', opacity: 'opacity', shadow: 'box-shadow', transform: 'transform', none: 'none' }), normal: { transitionBehavior: 'normal' }, discrete: { transitionBehavior: 'allow-discrete' } })
// prettier-ignore
group('underline', { offset: scopedRule('underlineOffset', propertyRule('textUnderlineOffset', (key) => `${Number(key)}px`)) })
group('underlineOffset', { auto: { textUnderlineOffset: 'auto' } })
group('visibility', values('visibility', { visible: 'visible', hidden: 'hidden', collapse: 'collapse' }))
group('whitespace', values('whiteSpace', { normal: 'normal', nowrap: 'nowrap', pre: 'pre', 'pre-line': 'pre-line', 'pre-wrap': 'pre-wrap', 'break-spaces': 'break-spaces' }))
group('will', { change: scopedRule('willChange', propertyRule('willChange')) })
group('willChange', values('willChange', { auto: 'auto', scroll: 'scroll-position', contents: 'contents', transform: 'transform' }))
group('wrap', values('overflowWrap', { 'break-word': 'break-word', anywhere: 'anywhere', normal: 'normal' }))
export const absolute: Utility['absolute'] = utility<Utility['absolute']>('absolute', { position: 'absolute' })
export const accent: Utility['accent'] = utility<Utility['accent']>('accent', colorRule('accentColor'))
export const active: Utility['active'] = utility<Utility['active']>('active', variantRule(':active'))
export const after: Utility['after'] = utility<Utility['after']>('after', variantRule('::after'))
export const align: Utility['align'] = utility<Utility['align']>('align', propertyRule('verticalAlign'))
export const animate: Utility['animate'] = utility<Utility['animate']>('animate', propertyRule('animation'))
export const antialiased: Utility['antialiased'] = utility<Utility['antialiased']>('antialiased', { WebkitFontSmoothing: 'antialiased', MozOsxFontSmoothing: 'grayscale' })
export const appearance: Utility['appearance'] = utility<Utility['appearance']>('appearance', propertyRule('appearance'), 'appearance')
export const aria: Utility['aria'] = utility<Utility['aria']>('aria', variantRule('[aria]'))
export const ariaChecked: Utility['ariaChecked'] = utility<Utility['ariaChecked']>('ariaChecked', variantRule('[aria-checked=true]'))
export const ariaDisabled: Utility['ariaDisabled'] = utility<Utility['ariaDisabled']>('ariaDisabled', variantRule('[aria-disabled=true]'))
export const ariaExpanded: Utility['ariaExpanded'] = utility<Utility['ariaExpanded']>('ariaExpanded', variantRule('[aria-expanded=true]'))
export const ariaSelected: Utility['ariaSelected'] = utility<Utility['ariaSelected']>('ariaSelected', variantRule('[aria-selected=true]'))
// prettier-ignore
export const aspect: Utility['aspect'] = utility<Utility['aspect']>('aspect', propertyRule('aspectRatio', (key) => (Number.isFinite(Number(key)) ? `${Number(key) * 4} / 9` : key)), 'aspect')
group('aspect', { auto: { aspectRatio: 'auto' }, video: { aspectRatio: '16 / 9' } })
export const atLg: Utility['atLg'] = utility<Utility['atLg']>('atLg', variantRule('container(width >= 1024px)'))
export const atMd: Utility['atMd'] = utility<Utility['atMd']>('atMd', variantRule('container(width >= 768px)'))
export const atSm: Utility['atSm'] = utility<Utility['atSm']>('atSm', variantRule('container(width >= 640px)'))
export const auto: Utility['auto'] = utility<Utility['auto']>('auto', {}, 'auto')
export const autofill: Utility['autofill'] = utility<Utility['autofill']>('autofill', variantRule(':autofill'))
export const backdrop: Utility['backdrop'] = utility<Utility['backdrop']>('backdrop', {}, 'backdrop')
export const backface: Utility['backface'] = utility<Utility['backface']>('backface', {}, 'backface')
group('backdrop', { filter: scopedRule('backdropFilter', propertyRule('backdropFilter')), blur: scopedRule('backdropFilter', filterRule('backdropFilter', 'blur', 'px')), brightness: scopedRule('backdropFilter', filterRule('backdropFilter', 'brightness')), contrast: scopedRule('backdropFilter', filterRule('backdropFilter', 'contrast')), grayscale: scopedRule('backdropFilter', defaultFilterRule('backdropFilter', 'grayscale', '100%')), hue: scopedRule('backdropHue', {}), invert: scopedRule('backdropFilter', defaultFilterRule('backdropFilter', 'invert', '100%')), opacity: scopedRule('backdropFilter', filterRule('backdropFilter', 'opacity')), saturate: scopedRule('backdropFilter', filterRule('backdropFilter', 'saturate')), sepia: scopedRule('backdropFilter', defaultFilterRule('backdropFilter', 'sepia', '100%')) })
group('backdropHue', { rotate: scopedRule('backdropFilter', filterRule('backdropFilter', 'hue-rotate', 'deg')) })
group('backface', values('backfaceVisibility', { hidden: 'hidden', visible: 'visible' }))
export const basis: Utility['basis'] = utility<Utility['basis']>('basis', lengthRule('flexBasis'))
export const before: Utility['before'] = utility<Utility['before']>('before', variantRule('::before'))
export const bg: Utility['bg'] = utility<Utility['bg']>('bg', colorRule('background'), 'bg')
export const block: Utility['block'] = utility<Utility['block']>('block', { display: 'block' })
export const blur: Utility['blur'] = utility<Utility['blur']>('blur', filterRule('filter', 'blur', 'px'))
export const border: Utility['border'] = utility<Utility['border']>('border', borderRule)
export const bottom: Utility['bottom'] = utility<Utility['bottom']>('bottom', positionRule('bottom'))
export const box: Utility['box'] = utility<Utility['box']>('box', {}, 'box')
export const break_: Utility['break'] = utility<Utility['break']>('break', {}, 'break')
export { break_ as break }
export const brightness: Utility['brightness'] = utility<Utility['brightness']>('brightness', filterRule('filter', 'brightness'))
export const caption: Utility['caption'] = utility<Utility['caption']>('caption', {}, 'caption')
export const capitalize: Utility['capitalize'] = utility<Utility['capitalize']>('capitalize', { textTransform: 'capitalize' })
export const caret: Utility['caret'] = utility<Utility['caret']>('caret', colorRule('caretColor'))
export const checked: Utility['checked'] = utility<Utility['checked']>('checked', variantRule(':checked'))
export const child: Utility['child'] = utility<Utility['child']>('child', variantRule('> *'))
export const clear: Utility['clear'] = utility<Utility['clear']>('clear', {}, 'clear')
export const col: Utility['col'] = utility<Utility['col']>('col', columnRule, 'col')
export const columns: Utility['columns'] = utility<Utility['columns']>('columns', propertyRule('columns'), 'columns')
group('columns', { auto: { columns: 'auto' } })
export const color: Utility['color'] = utility<Utility['color']>('color', colorRule('color'))
export const cols: Utility['cols'] = utility<Utility['cols']>('cols', scopedRule('cols', columnsRule))
export const colStart: Utility['colStart'] = utility<Utility['colStart']>('colStart', propertyRule('gridColumnStart'))
export const container: Utility['container'] = utility<Utility['container']>('container', { width: '100%' })
export const content: Utility['content'] = utility<Utility['content']>('content', propertyRule('content'), 'content')
export const contrast: Utility['contrast'] = utility<Utility['contrast']>('contrast', filterRule('filter', 'contrast'))
export const contrastLess: Utility['contrastLess'] = utility<Utility['contrastLess']>('contrastLess', variantRule('media(prefers-contrast: less)'))
export const contrastMore: Utility['contrastMore'] = utility<Utility['contrastMore']>('contrastMore', variantRule('media(prefers-contrast: more)'))
export const css: Utility['css'] = utility<Utility['css']>('css', splitRule)
export const cursor: Utility['cursor'] = utility<Utility['cursor']>('cursor', propertyRule('cursor'), 'cursor')
export const dark: Utility['dark'] = utility<Utility['dark']>('dark', darkRule)
export const data: Utility['data'] = utility<Utility['data']>('data', variantRule('[data]'))
export const dataActive: Utility['dataActive'] = utility<Utility['dataActive']>('dataActive', variantRule('[data-active]'))
export const decoration: Utility['decoration'] = utility<Utility['decoration']>('decoration', colorRule('textDecorationColor'), 'decoration')
// prettier-ignore
export const delay: Utility['delay'] = utility<Utility['delay']>('delay', numericRule((key) => ({ transitionDelay: `${key}ms` })))
export const descendant: Utility['descendant'] = utility<Utility['descendant']>('descendant', variantRule(' *'))
export const disabled: Utility['disabled'] = utility<Utility['disabled']>('disabled', variantRule(':disabled'))
export const display: Utility['display'] = utility<Utility['display']>('display', propertyRule('display'), 'display')
export const divide: Utility['divide'] = utility<Utility['divide']>('divide', colorRule('borderColor'), 'divide')
// prettier-ignore
export const duration: Utility['duration'] = utility<Utility['duration']>('duration', numericRule((key) => ({ transitionDuration: `${key}ms` })), 'duration')
group('duration', { initial: { transitionDuration: 'initial' } })
export const ease: Utility['ease'] = utility<Utility['ease']>('ease', propertyRule('transitionTimingFunction'), 'ease')
group('ease', { linear: { transitionTimingFunction: 'linear' }, in: { transitionTimingFunction: 'cubic-bezier(0.4, 0, 1, 1)' }, out: { transitionTimingFunction: 'cubic-bezier(0, 0, 0.2, 1)' }, initial: { transitionTimingFunction: 'initial' } })
group('ease', { in: scopedRule('easeIn', { transitionTimingFunction: 'cubic-bezier(0.4, 0, 1, 1)' }) })
group('easeIn', { out: { transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)' } })
export const empty: Utility['empty'] = utility<Utility['empty']>('empty', variantRule(':empty'))
export const enabled: Utility['enabled'] = utility<Utility['enabled']>('enabled', variantRule(':enabled'))
export const end: Utility['end'] = utility<Utility['end']>('end', positionRule('insetInlineEnd'))
export const even: Utility['even'] = utility<Utility['even']>('even', variantRule(':nth-child(even)'))
export const field: Utility['field'] = utility<Utility['field']>('field', {}, 'field')
export const file: Utility['file'] = utility<Utility['file']>('file', variantRule('::file-selector-button'))
export const fill: Utility['fill'] = utility<Utility['fill']>('fill', colorRule('fill'))
export const filter: Utility['filter'] = utility<Utility['filter']>('filter', propertyRule('filter'), 'filter')
export const first: Utility['first'] = utility<Utility['first']>('first', variantRule(':first-child'))
export const firstLetter: Utility['firstLetter'] = utility<Utility['firstLetter']>('firstLetter', variantRule('::first-letter'))
export const firstLine: Utility['firstLine'] = utility<Utility['firstLine']>('firstLine', variantRule('::first-line'))
export const firstOfType: Utility['firstOfType'] = utility<Utility['firstOfType']>('firstOfType', variantRule(':first-of-type'))
export const fixed: Utility['fixed'] = utility<Utility['fixed']>('fixed', { position: 'fixed' })
export const flex: Utility['flex'] = utility<Utility['flex']>('flex', flexRule)
export const float: Utility['float'] = utility<Utility['float']>('float', {}, 'float')
group('float', values('float', { right: 'right', left: 'left', 'inline-start': 'inline-start', 'inline-end': 'inline-end', none: 'none' }))
export const flow: Utility['flow'] = utility<Utility['flow']>('flow', {}, 'flow')
export const focus: Utility['focus'] = utility<Utility['focus']>('focus', variantRule(':focus'))
export const focusVisible: Utility['focusVisible'] = utility<Utility['focusVisible']>('focusVisible', variantRule(':focus-visible'))
export const focusWithin: Utility['focusWithin'] = utility<Utility['focusWithin']>('focusWithin', variantRule(':focus-within'))
// prettier-ignore
export const font: Utility['font'] = utility<Utility['font']>('font', scopedRule('font', numericRule((key) => ({ fontWeight: Number(key) }))))
export const forcedColorAdjust: Utility['forcedColorAdjust'] = utility<Utility['forcedColorAdjust']>('forcedColorAdjust', {}, 'forcedColorAdjust')
group('forcedColorAdjust', values('forcedColorAdjust', { auto: 'auto', none: 'none' }))
export const forcedColors: Utility['forcedColors'] = utility<Utility['forcedColors']>('forcedColors', variantRule('media(forced-colors: active)'))
export const from: Utility['from'] = utility<Utility['from']>('from', colorRule('--tw-gradient-from'))
export const gap: Utility['gap'] = utility<Utility['gap']>('gap', scopedRule('gap', scaleRule('gap')))
export const grayscale: Utility['grayscale'] = utility<Utility['grayscale']>('grayscale', defaultFilterRule('filter', 'grayscale', '100%'))
export const grid: Utility['grid'] = utility<Utility['grid']>('grid', { display: 'grid' }, 'grid')
export const group_: Utility['group'] = utility<Utility['group']>('group', variantRule('.group &'))
export { group_ as group }
export const groupFocus: Utility['groupFocus'] = utility<Utility['groupFocus']>('groupFocus', variantRule('.group:focus &'))
export const groupHover: Utility['groupHover'] = utility<Utility['groupHover']>('groupHover', variantRule('.group:hover &'))
export const grow: Utility['grow'] = utility<Utility['grow']>('grow', propertyRule('flexGrow'))
export const h: Utility['h'] = utility<Utility['h']>('h', lengthRule('height', '100vh'))
export const has: Utility['has'] = utility<Utility['has']>('has', variantRule(':has(*)'))
export const height: Utility['height'] = utility<Utility['height']>('height', lengthRule('height', '100vh'))
export const hidden: Utility['hidden'] = utility<Utility['hidden']>('hidden', { display: 'none' })
export const hover: Utility['hover'] = utility<Utility['hover']>('hover', variantRule(':hover'))
export const hue: Utility['hue'] = utility<Utility['hue']>('hue', {}, 'hue')
group('hue', { rotate: scopedRule('filter', filterRule('filter', 'hue-rotate', 'deg')) })
export const hyphens: Utility['hyphens'] = utility<Utility['hyphens']>('hyphens', {}, 'hyphens')
export const indeterminate: Utility['indeterminate'] = utility<Utility['indeterminate']>('indeterminate', variantRule(':indeterminate'))
export const indent: Utility['indent'] = utility<Utility['indent']>('indent', lengthRule('textIndent'))
export const inline: Utility['inline'] = utility<Utility['inline']>('inline', { display: 'inline' }, 'inline')
export const inlineBlock: Utility['inlineBlock'] = utility<Utility['inlineBlock']>('inlineBlock', { display: 'inline-block' })
export const inlineFlex: Utility['inlineFlex'] = utility<Utility['inlineFlex']>('inlineFlex', { display: 'inline-flex' })
export const inset: Utility['inset'] = utility<Utility['inset']>('inset', positionRule('inset'), 'inset')
export const invalid: Utility['invalid'] = utility<Utility['invalid']>('invalid', variantRule(':invalid'))
export const invert: Utility['invert'] = utility<Utility['invert']>('invert', defaultFilterRule('filter', 'invert', '100%'))
export const isolation: Utility['isolation'] = utility<Utility['isolation']>('isolation', {}, 'isolation')
export const italic: Utility['italic'] = utility<Utility['italic']>('italic', { fontStyle: 'italic' })
export const items: Utility['items'] = utility<Utility['items']>('items', {}, 'items')
export const justify: Utility['justify'] = utility<Utility['justify']>('justify', {}, 'justify')
export const landscape: Utility['landscape'] = utility<Utility['landscape']>('landscape', variantRule('media(orientation: landscape)'))
export const last: Utility['last'] = utility<Utility['last']>('last', variantRule(':last-child'))
export const lastOfType: Utility['lastOfType'] = utility<Utility['lastOfType']>('lastOfType', variantRule(':last-of-type'))
export const leading: Utility['leading'] = utility<Utility['leading']>('leading', scaleRule('lineHeight'))
export const left: Utility['left'] = utility<Utility['left']>('left', positionRule('left'))
export const lg: Utility['lg'] = utility<Utility['lg']>('lg', mediaRule('1024px'))
export const light: Utility['light'] = utility<Utility['light']>('light', variantRule('.light &'))
export const line: Utility['line'] = utility<Utility['line']>('line', {}, 'line')
export const lineThrough: Utility['lineThrough'] = utility<Utility['lineThrough']>('lineThrough', { textDecorationLine: 'line-through' })
export const liningNums: Utility['liningNums'] = utility<Utility['liningNums']>('liningNums', { fontVariantNumeric: 'lining-nums' })
export const list: Utility['list'] = utility<Utility['list']>('list', propertyRule('listStyleType'), 'list')
export const lowercase: Utility['lowercase'] = utility<Utility['lowercase']>('lowercase', { textTransform: 'lowercase' })
export const ltr: Utility['ltr'] = utility<Utility['ltr']>('ltr', variantRule('[dir=ltr] &'))
export const m: Utility['m'] = utility<Utility['m']>('m', spacingRule('margin'))
export const margin: Utility['margin'] = utility<Utility['margin']>('margin', spacingRule('margin'))
export const marker: Utility['marker'] = utility<Utility['marker']>('marker', variantRule('::marker'))
export const mask: Utility['mask'] = utility<Utility['mask']>('mask', propertyRule('maskImage'), 'mask')
export const max: Utility['max'] = utility<Utility['max']>('max', {}, 'max')
export const maxMd: Utility['maxMd'] = utility<Utility['maxMd']>('maxMd', variantRule('media(width < 768px)'))
export const maxSm: Utility['maxSm'] = utility<Utility['maxSm']>('maxSm', variantRule('media(width < 640px)'))
export const mb: Utility['mb'] = utility<Utility['mb']>('mb', spacingRule('marginBottom'))
export const md: Utility['md'] = utility<Utility['md']>('md', mediaRule('768px'))
export const me: Utility['me'] = utility<Utility['me']>('me', spacingRule('marginInlineEnd'))
export const min: Utility['min'] = utility<Utility['min']>('min', {}, 'min')
export const mix: Utility['mix'] = utility<Utility['mix']>('mix', {}, 'mix')
export const ml: Utility['ml'] = utility<Utility['ml']>('ml', spacingRule('marginLeft'))
export const motionReduce: Utility['motionReduce'] = utility<Utility['motionReduce']>('motionReduce', variantRule('media(prefers-reduced-motion: reduce)'))
export const motionSafe: Utility['motionSafe'] = utility<Utility['motionSafe']>('motionSafe', variantRule('media(prefers-reduced-motion: no-preference)'))
export const mr: Utility['mr'] = utility<Utility['mr']>('mr', spacingRule('marginRight'))
export const ms: Utility['ms'] = utility<Utility['ms']>('ms', spacingRule('marginInlineStart'))
export const mt: Utility['mt'] = utility<Utility['mt']>('mt', spacingRule('marginTop'))
export const mx: Utility['mx'] = utility<Utility['mx']>('mx', scopedRule('mx', spacingRule('marginLeft', 'marginRight')))
group('mx', { auto: { marginLeft: 'auto', marginRight: 'auto' } })
export const my: Utility['my'] = utility<Utility['my']>('my', scopedRule('my', spacingRule('marginBottom', 'marginTop')))
group('my', { auto: { marginBottom: 'auto', marginTop: 'auto' } })
export const none: Utility['none'] = utility<Utility['none']>('none', { textDecorationLine: 'none' })
export const normal: Utility['normal'] = utility<Utility['normal']>('normal', { fontStyle: 'normal' })
export const not: Utility['not'] = utility<Utility['not']>('not', {}, 'not')
export const notSr: Utility['notSr'] = utility<Utility['notSr']>('notSr', {}, 'notSr')
export const object: Utility['object'] = utility<Utility['object']>('object', propertyRule('objectPosition'), 'object')
export const odd: Utility['odd'] = utility<Utility['odd']>('odd', variantRule(':nth-child(odd)'))
export const oldstyleNums: Utility['oldstyleNums'] = utility<Utility['oldstyleNums']>('oldstyleNums', { fontVariantNumeric: 'oldstyle-nums' })
export const only: Utility['only'] = utility<Utility['only']>('only', variantRule(':only-child'))
export const onlyOfType: Utility['onlyOfType'] = utility<Utility['onlyOfType']>('onlyOfType', variantRule(':only-of-type'))
export const opacity: Utility['opacity'] = utility<Utility['opacity']>('opacity', opacityRule('opacity'))
export const optional: Utility['optional'] = utility<Utility['optional']>('optional', variantRule(':optional'))
export const order: Utility['order'] = utility<Utility['order']>('order', propertyRule('order'))
export const ordinal: Utility['ordinal'] = utility<Utility['ordinal']>('ordinal', { fontVariantNumeric: 'ordinal' })
export const origin: Utility['origin'] = utility<Utility['origin']>('origin', propertyRule('transformOrigin'), 'origin')
export const outline: Utility['outline'] = utility<Utility['outline']>('outline', outlineRule)
export const overline: Utility['overline'] = utility<Utility['overline']>('overline', { textDecorationLine: 'overline' })
export const overflow: Utility['overflow'] = utility<Utility['overflow']>('overflow', {}, 'overflow')
export const overscroll: Utility['overscroll'] = utility<Utility['overscroll']>('overscroll', {}, 'overscroll')
export const p: Utility['p'] = utility<Utility['p']>('p', spacingRule('padding'))
export const padding: Utility['padding'] = utility<Utility['padding']>('padding', spacingRule('padding'))
export const pb: Utility['pb'] = utility<Utility['pb']>('pb', spacingRule('paddingBottom'))
export const pe: Utility['pe'] = utility<Utility['pe']>('pe', spacingRule('paddingInlineEnd'))
export const peer: Utility['peer'] = utility<Utility['peer']>('peer', variantRule('.peer ~ &'))
export const peerFocus: Utility['peerFocus'] = utility<Utility['peerFocus']>('peerFocus', variantRule('.peer:focus ~ &'))
export const peerHover: Utility['peerHover'] = utility<Utility['peerHover']>('peerHover', variantRule('.peer:hover ~ &'))
export const perspective: Utility['perspective'] = utility<Utility['perspective']>('perspective', propertyRule('perspective'), 'perspective')
export const placeholder: Utility['placeholder'] = utility<Utility['placeholder']>('placeholder', variantRule('::placeholder'))
export const placeholderShown: Utility['placeholderShown'] = utility<Utility['placeholderShown']>('placeholderShown', variantRule(':placeholder-shown'))
export const place: Utility['place'] = utility<Utility['place']>('place', {}, 'place')
export const pl: Utility['pl'] = utility<Utility['pl']>('pl', spacingRule('paddingLeft'))
export const pointer: Utility['pointer'] = utility<Utility['pointer']>('pointer', {}, 'pointer')
export const pointerCoarse: Utility['pointerCoarse'] = utility<Utility['pointerCoarse']>('pointerCoarse', variantRule('media(pointer: coarse)'))
export const pointerFine: Utility['pointerFine'] = utility<Utility['pointerFine']>('pointerFine', variantRule('media(pointer: fine)'))
export const portrait: Utility['portrait'] = utility<Utility['portrait']>('portrait', variantRule('media(orientation: portrait)'))
export const position: Utility['position'] = utility<Utility['position']>('position', {}, 'position')
export const pr: Utility['pr'] = utility<Utility['pr']>('pr', spacingRule('paddingRight'))
export const prefersDark: Utility['prefersDark'] = utility<Utility['prefersDark']>('prefersDark', variantRule('media(prefers-color-scheme: dark)'))
export const print: Utility['print'] = utility<Utility['print']>('print', variantRule('media(print)'))
export const proportionalNums: Utility['proportionalNums'] = utility<Utility['proportionalNums']>('proportionalNums', { fontVariantNumeric: 'proportional-nums' })
export const ps: Utility['ps'] = utility<Utility['ps']>('ps', spacingRule('paddingInlineStart'))
export const pt: Utility['pt'] = utility<Utility['pt']>('pt', spacingRule('paddingTop'))
export const px: Utility['px'] = utility<Utility['px']>('px', spacingRule('paddingLeft', 'paddingRight'))
export const py: Utility['py'] = utility<Utility['py']>('py', spacingRule('paddingBottom', 'paddingTop'))
export const readOnly: Utility['readOnly'] = utility<Utility['readOnly']>('readOnly', variantRule(':read-only'))
export const relative: Utility['relative'] = utility<Utility['relative']>('relative', { position: 'relative' })
export const required: Utility['required'] = utility<Utility['required']>('required', variantRule(':required'))
export const resize: Utility['resize'] = utility<Utility['resize']>('resize', { resize: 'both' }, 'resize')
export const right: Utility['right'] = utility<Utility['right']>('right', positionRule('right'))
export const rotate: Utility['rotate'] = utility<Utility['rotate']>('rotate', transformRule('rotate', 'deg'))
export const rounded: Utility['rounded'] = utility<Utility['rounded']>('rounded', roundedRule(), 'rounded')
export const row: Utility['row'] = utility<Utility['row']>('row', rowRule, 'row')
export const rows: Utility['rows'] = utility<Utility['rows']>('rows', scopedRule('rows', rowsRule))
export const rtl: Utility['rtl'] = utility<Utility['rtl']>('rtl', variantRule('[dir=rtl] &'))
export const saturate: Utility['saturate'] = utility<Utility['saturate']>('saturate', filterRule('filter', 'saturate'))
export const scale: Utility['scale'] = utility<Utility['scale']>('scale', transformRule('scale'))
export const scheme: Utility['scheme'] = utility<Utility['scheme']>('scheme', {}, 'scheme')
export const scroll: Utility['scroll'] = utility<Utility['scroll']>('scroll', {}, 'scroll')
export const scrollbar: Utility['scrollbar'] = utility<Utility['scrollbar']>('scrollbar', {}, 'scrollbar')
export const select: Utility['select'] = utility<Utility['select']>('select', {}, 'select')
export const selection: Utility['selection'] = utility<Utility['selection']>('selection', variantRule('::selection'))
export const self: Utility['self'] = utility<Utility['self']>('self', {}, 'self')
export const sepia: Utility['sepia'] = utility<Utility['sepia']>('sepia', defaultFilterRule('filter', 'sepia', '100%'))
export const shadow: Utility['shadow'] = utility<Utility['shadow']>('shadow', propertyRule('boxShadow'), 'shadow')
export const shrink: Utility['shrink'] = utility<Utility['shrink']>('shrink', propertyRule('flexShrink'))
export const size: Utility['size'] = utility<Utility['size']>('size', sizeRule, 'size')
export const skew: Utility['skew'] = utility<Utility['skew']>('skew', transformRule('skew', 'deg'), 'skew')
group('skew', { x: transformRule('skewX', 'deg'), y: transformRule('skewY', 'deg') })
export const slashedZero: Utility['slashedZero'] = utility<Utility['slashedZero']>('slashedZero', { fontVariantNumeric: 'slashed-zero' })
export const sm: Utility['sm'] = utility<Utility['sm']>('sm', mediaRule('640px'))
export const snap: Utility['snap'] = utility<Utility['snap']>('snap', {}, 'snap')
export const sr: Utility['sr'] = utility<Utility['sr']>('sr', {}, 'sr')
export const stackedFractions: Utility['stackedFractions'] = utility<Utility['stackedFractions']>('stackedFractions', { fontVariantNumeric: 'stacked-fractions' })
export const start: Utility['start'] = utility<Utility['start']>('start', positionRule('insetInlineStart'))
export const static_: Utility['static'] = utility<Utility['static']>('static', { position: 'static' })
export { static_ as static }
export const stroke: Utility['stroke'] = utility<Utility['stroke']>('stroke', colorRule('stroke'))
export const subpixel: Utility['subpixel'] = utility<Utility['subpixel']>('subpixel', {}, 'subpixel')
group('subpixel', { antialiased: { WebkitFontSmoothing: 'auto', MozOsxFontSmoothing: 'auto' } })
export const supports: Utility['supports'] = utility<Utility['supports']>('supports', variantRule('@supports'))
export const table: Utility['table'] = utility<Utility['table']>('table', { display: 'table' }, 'table')
// prettier-ignore
export const tab: Utility['tab'] = utility<Utility['tab']>('tab', numericRule((key) => ({ tabSize: Number(key) })))
export const tabularNums: Utility['tabularNums'] = utility<Utility['tabularNums']>('tabularNums', { fontVariantNumeric: 'tabular-nums' })
export const target: Utility['target'] = utility<Utility['target']>('target', variantRule(':target'))
export const text: Utility['text'] = utility<Utility['text']>('text', textRule)
export const to: Utility['to'] = utility<Utility['to']>('to', colorRule('--tw-gradient-to'))
export const top: Utility['top'] = utility<Utility['top']>('top', positionRule('top'))
export const touch: Utility['touch'] = utility<Utility['touch']>('touch', {}, 'touch')
export const tracking: Utility['tracking'] = utility<Utility['tracking']>('tracking', scaleRule('letterSpacing'), 'tracking')
export const transform: Utility['transform'] = utility<Utility['transform']>('transform', propertyRule('transform'), 'transform')
export const transition: Utility['transition'] = utility<Utility['transition']>('transition', propertyRule('transitionProperty'), 'transition')
export const translate: Utility['translate'] = utility<Utility['translate']>('translate', propertyRule('transform'), 'translate')
group('translate', { full: { transform: 'translate(100%, 100%)' }, none: { transform: 'none' }, px: { transform: 'translate(1px, 1px)' }, x: translateRule('X'), y: translateRule('Y') })
export const truncate: Utility['truncate'] = utility<Utility['truncate']>('truncate', { overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' })
export const underline: Utility['underline'] = utility<Utility['underline']>('underline', { textDecorationLine: 'underline' }, 'underline')
export const uppercase: Utility['uppercase'] = utility<Utility['uppercase']>('uppercase', { textTransform: 'uppercase' })
export const valid: Utility['valid'] = utility<Utility['valid']>('valid', variantRule(':valid'))
export const visibility: Utility['visibility'] = utility<Utility['visibility']>('visibility', {}, 'visibility')
export const visited: Utility['visited'] = utility<Utility['visited']>('visited', variantRule(':visited'))
export const w: Utility['w'] = utility<Utility['w']>('w', lengthRule('width', '100vw'))
export const whitespace: Utility['whitespace'] = utility<Utility['whitespace']>('whitespace', {}, 'whitespace')
export const width: Utility['width'] = utility<Utility['width']>('width', lengthRule('width', '100vw'))
export const will: Utility['will'] = utility<Utility['will']>('will', {}, 'will')
export const wrap: Utility['wrap'] = utility<Utility['wrap']>('wrap', {}, 'wrap')
export const xl: Utility['xl'] = utility<Utility['xl']>('xl', mediaRule('1280px'))
export const xl2: Utility['xl2'] = utility<Utility['xl2']>('xl2', mediaRule('1536px'))
export const z: Utility['z'] = utility<Utility['z']>('z', propertyRule('zIndex'), 'z')
group('z', { auto: { zIndex: 'auto' } })
export const zoom: Utility['zoom'] = utility<Utility['zoom']>('zoom', propertyRule('zoom'))
export const define = <T = Chain>(name: string, css: RuntimeStyle, scopeName?: string): T => utility<T>(name, css, scopeName)
