import { borderRule, borderSideRule, colorRule, columnRule, columnsRule, controls, darkRule, defaultFilterRule, divideRule, filterRule, flexRule, group, lengthRule, mediaRule, numericRule, opacityRule, outlineRule, positionRule, propertyRule, roundedRule, rowRule, rowsRule, scaleRule, scopedRule, sizePropsRule, sizeRule, spacingRule, splitRule, textRule, transformRule, translateRule, utility as u, values, variantRule } from './utils.ts'
import type { C, RuntimeStyle, U } from './types.ts'
controls('active', 'after', 'aria', 'ariaChecked', 'ariaDisabled', 'ariaExpanded', 'ariaSelected', 'atLg', 'atMd', 'atSm', 'autofill', 'before', 'bg', 'border', 'checked', 'child', 'contrastLess', 'contrastMore', 'css', 'dark', 'data', 'dataActive', 'descendant', 'disabled', 'empty', 'enabled', 'even', 'file', 'fill', 'first', 'firstLetter', 'firstLine', 'firstOfType', 'focus', 'focusVisible', 'focusWithin', 'forcedColors', 'group', 'groupFocus', 'groupHover', 'has', 'hover', 'indeterminate', 'invalid', 'landscape', 'last', 'lastOfType', 'lg', 'light', 'ltr', 'maxMd', 'maxSm', 'md', 'motionReduce', 'motionSafe', 'odd', 'only', 'onlyOfType', 'optional', 'peer', 'peerFocus', 'peerHover', 'placeholder', 'placeholderShown', 'pointerCoarse', 'pointerFine', 'portrait', 'prefersDark', 'print', 'readOnly', 'required', 'rtl', 'selection', 'shadow', 'sm', 'stroke', 'supports', 'target', 'text', 'valid', 'visited', 'xl', 'xl2')
const contentValues = { baseline: 'baseline', center: 'center', end: 'flex-end', 'flex-end': 'flex-end', 'flex-start': 'flex-start', normal: 'normal', 'safe center': 'safe center', 'safe end': 'safe end', 'safe flex-end': 'safe flex-end', 'space-around': 'space-around', 'space-be_een': 'space-between', 'space-between': 'space-between', 'space-evenly': 'space-evenly', start: 'flex-start', stretch: 'stretch' }
const itemValues = { baseline: 'baseline', center: 'center', end: 'flex-end', 'flex-end': 'flex-end', 'flex-start': 'flex-start', normal: 'normal', 'last baseline': 'last baseline', 'safe center': 'safe center', 'safe end': 'safe end', 'safe flex-end': 'safe flex-end', start: 'flex-start', stretch: 'stretch' }
const boxValues = { auto: 'auto', avoid: 'avoid', all: 'all', 'avoid-page': 'avoid-page', 'avoid-column': 'avoid-column', page: 'page', left: 'left', right: 'right', column: 'column' }
const blendValues = { normal: 'normal', multiply: 'multiply', screen: 'screen', overlay: 'overlay', darken: 'darken', lighten: 'lighten', 'color-dodge': 'color-dodge', 'color-burn': 'color-burn', 'hard-light': 'hard-light', 'soft-light': 'soft-light', difference: 'difference', exclusion: 'exclusion', hue: 'hue', saturation: 'saturation', color: 'color', luminosity: 'luminosity', 'plus-darker': 'plus-darker', 'plus-lighter': 'plus-lighter' }
const positionValues = { bottom: 'bottom', 'bottom left': 'bottom left', 'bottom right': 'bottom right', center: 'center', left: 'left', right: 'right', top: 'top', 'top left': 'top left', 'top right': 'top right' }
const repeatValues = { repeat: 'repeat', 'repeat-x': 'repeat-x', 'repeat-y': 'repeat-y', space: 'space', round: 'round', 'no-repeat': 'no-repeat' }
const cursorValues = { alias: 'alias', auto: 'auto', cell: 'cell', copy: 'copy', crosshair: 'crosshair', default: 'default', grab: 'grab', grabbing: 'grabbing', help: 'help', move: 'move', none: 'none', pointer: 'pointer', progress: 'progress', text: 'text', wait: 'wait' }
group('auto', { cols: scopedRule('autoCols', propertyRule('gridAutoColumns')), rows: scopedRule('autoRows', propertyRule('gridAutoRows')) })
group('autoCols', { ...values('gridAutoColumns', { auto: 'auto', 'min-content': 'min-content', 'max-content': 'max-content', 'minmax(0, 1fr)': 'minmax(0, 1fr)' }) })
group('autoRows', { ...values('gridAutoRows', { auto: 'auto', 'min-content': 'min-content', 'max-content': 'max-content', 'minmax(0, 1fr)': 'minmax(0, 1fr)' }) })
group('bg', { ...values('backgroundAttachment', { fixed: 'fixed', local: 'local', scroll: 'scroll' }), ...values('backgroundSize', { auto: 'auto', cover: 'cover', contain: 'contain' }), blend: scopedRule('bgBlend', {}), clip: scopedRule('bgClip', {}), origin: scopedRule('bgOrigin', {}), position: scopedRule('bgPosition', propertyRule('backgroundPosition')), repeat: scopedRule('bgRepeat', {}), size: scopedRule('bgSize', scaleRule('backgroundSize')) })
group('bgBlend', values('backgroundBlendMode', blendValues))
group('bgClip', values('backgroundClip', { 'border-box': 'border-box', 'padding-box': 'padding-box', 'content-box': 'content-box', text: 'text' }))
group('bgOrigin', values('backgroundOrigin', { 'border-box': 'border-box', 'padding-box': 'padding-box', 'content-box': 'content-box' }))
group('bgPosition', values('backgroundPosition', positionValues))
group('bgRepeat', values('backgroundRepeat', repeatValues))
group('border', { ...values('borderStyle', { solid: 'solid', dashed: 'dashed', dotted: 'dotted', double: 'double', hidden: 'hidden', none: 'none' }), b: borderSideRule('borderBottom'), be: borderSideRule('borderBlockEnd'), bs: borderSideRule('borderBlockStart'), collapse: { borderCollapse: 'collapse' }, e: borderSideRule('borderInlineEnd'), l: borderSideRule('borderLeft'), r: borderSideRule('borderRight'), s: borderSideRule('borderInlineStart'), separate: { borderCollapse: 'separate' }, t: borderSideRule('borderTop'), x: borderSideRule('borderLeft', 'borderRight'), y: borderSideRule('borderBottom', 'borderTop') })
group('box', { decoration: scopedRule('boxDecoration', {}), ...values('boxSizing', { 'border-box': 'border-box', 'content-box': 'content-box' }) })
group('boxDecoration', values('boxDecorationBreak', { clone: 'clone', slice: 'slice' }))
group('break', { after: scopedRule('breakAfter', {}), before: scopedRule('breakBefore', {}), inside: scopedRule('breakInside', {}), normal: { overflowWrap: 'normal', wordBreak: 'normal' }, 'break-all': { wordBreak: 'break-all' }, 'keep-all': { wordBreak: 'keep-all' } })
group('breakAfter', values('breakAfter', boxValues))
group('breakBefore', values('breakBefore', boxValues))
group('breakInside', values('breakInside', boxValues))
group('caption', values('captionSide', { top: 'top', bottom: 'bottom' }))
group('clear', values('clear', { left: 'left', right: 'right', both: 'both', 'inline-start': 'inline-start', 'inline-end': 'inline-end', none: 'none' }))
group('col', { auto: { gridColumn: 'auto' }, end: scopedRule('colEnd', propertyRule('gridColumnEnd')), full: { gridColumn: '1 / -1' }, span: numericRule((key) => ({ gridColumn: `span ${key} / span ${key}` })), start: scopedRule('colStart', propertyRule('gridColumnStart')) })
group('cols', { none: { gridTemplateColumns: 'none' }, subgrid: { gridTemplateColumns: 'subgrid' } })
group('content', { ...values('alignContent', contentValues), none: { content: 'none' } })
group('cursor', { ...values('cursor', cursorValues), all: scopedRule('cursorAll', {}), col: scopedRule('cursorCol', {}), context: scopedRule('cursorContext', {}), e: scopedRule('cursorE', {}), ew: scopedRule('cursorEw', {}), n: scopedRule('cursorN', {}), ne: scopedRule('cursorNe', {}), nesw: scopedRule('cursorNesw', {}), no: scopedRule('cursorNo', {}), not: scopedRule('cursorNot', {}), ns: scopedRule('cursorNs', {}), nw: scopedRule('cursorNw', {}), nwse: scopedRule('cursorNwse', {}), row: scopedRule('cursorRow', {}), s: scopedRule('cursorS', {}), se: scopedRule('cursorSe', {}), sw: scopedRule('cursorSw', {}), vertical: scopedRule('cursorVertical', {}), w: scopedRule('cursorW', {}), zoom: scopedRule('cursorZoom', {}) })
group('cursorAll', { scroll: { cursor: 'all-scroll' } })
group('cursorCol', { resize: { cursor: 'col-resize' } })
group('cursorContext', { menu: { cursor: 'context-menu' } })
group('cursorE', { resize: { cursor: 'e-resize' } })
group('cursorEw', { resize: { cursor: 'ew-resize' } })
group('cursorN', { resize: { cursor: 'n-resize' } })
group('cursorNe', { resize: { cursor: 'ne-resize' } })
group('cursorNesw', { resize: { cursor: 'nesw-resize' } })
group('cursorNo', { drop: { cursor: 'no-drop' } })
group('cursorNot', { allowed: { cursor: 'not-allowed' } })
group('cursorNs', { resize: { cursor: 'ns-resize' } })
group('cursorNw', { resize: { cursor: 'nw-resize' } })
group('cursorNwse', { resize: { cursor: 'nwse-resize' } })
group('cursorRow', { resize: { cursor: 'row-resize' } })
group('cursorS', { resize: { cursor: 's-resize' } })
group('cursorSe', { resize: { cursor: 'se-resize' } })
group('cursorSw', { resize: { cursor: 'sw-resize' } })
group('cursorVertical', { text: { cursor: 'vertical-text' } })
group('cursorW', { resize: { cursor: 'w-resize' } })
group('cursorZoom', { in: { cursor: 'zoom-in' }, out: { cursor: 'zoom-out' } })
group('decoration', { ...values('textDecorationStyle', { solid: 'solid', double: 'double', dotted: 'dotted', dashed: 'dashed', wavy: 'wavy' }), auto: { textDecorationThickness: 'auto' }, 'from-font': { textDecorationThickness: 'from-font' } })
group('display', values('display', { inline: 'inline', block: 'block', 'inline-block': 'inline-block', 'flow-root': 'flow-root', flex: 'flex', 'inline-flex': 'inline-flex', grid: 'grid', 'inline-grid': 'inline-grid', contents: 'contents', table: 'table', 'inline-table': 'inline-table', 'table-caption': 'table-caption', 'table-cell': 'table-cell', 'table-column': 'table-column', 'table-column-group': 'table-column-group', 'table-footer-group': 'table-footer-group', 'table-header-group': 'table-header-group', 'table-row-group': 'table-row-group', 'table-row': 'table-row', 'list-item': 'list-item', none: 'none' }))
group('divide', { ...values('borderStyle', { solid: 'solid', dashed: 'dashed', dotted: 'dotted', double: 'double', hidden: 'hidden', none: 'none' }), x: divideRule('borderLeftWidth', 'borderRightWidth'), y: divideRule('borderTopWidth', 'borderBottomWidth') })
group('field', { sizing: scopedRule('fieldSizing', {}) })
group('fieldSizing', values('fieldSizing', { fixed: 'fixed', content: 'content' }))
group('filter', { none: { filter: 'none' } })
group('flex', { ...values('flexDirection', { col: 'column', column: 'column', row: 'row', 'row-reverse': 'row-reverse', 'column-reverse': 'column-reverse' }), ...values('flexWrap', { nowrap: 'nowrap', wrap: 'wrap', 'wrap-reverse': 'wrap-reverse' }), auto: { flex: '1 1 auto' }, none: { flex: 'none' }, '0 auto': { flex: '0 auto' } })
group('flow', values('gridAutoFlow', { row: 'row', column: 'column', col: 'column', dense: 'dense', 'row dense': 'row dense', 'column dense': 'column dense' }))
group('font', { ...values('fontWeight', { bold: 700, medium: 500, normal: 400, semibold: 600, '100': 100, '200': 200, '300': 300, '400': 400, '500': 500, '600': 600, '700': 700, '800': 800, '900': 900 }), features: scopedRule('fontFeatures', propertyRule('fontFeatureSettings')), mono: { fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace' }, sans: { fontFamily: 'Arial, Helvetica, sans-serif' }, serif: { fontFamily: 'Georgia, Cambria, Times New Roman, Times, serif' }, stretch: scopedRule('fontStretch', propertyRule('fontStretch')) })
group('fontStretch', values('fontStretch', { 'ultra-condensed': 'ultra-condensed', 'extra-condensed': 'extra-condensed', condensed: 'condensed', 'semi-condensed': 'semi-condensed', normal: 'normal', 'semi-expanded': 'semi-expanded', expanded: 'expanded', 'extra-expanded': 'extra-expanded', 'ultra-expanded': 'ultra-expanded' }))
group('gap', { x: scaleRule('columnGap'), y: scaleRule('rowGap') })
group('grid', { cols: scopedRule('cols', columnsRule), flow: scopedRule('flow', {}), rows: scopedRule('rows', rowsRule) })
group('hyphens', values('hyphens', { none: 'none', manual: 'manual', auto: 'auto' }))
group('inline', { block: { display: 'inline-block' }, flex: { display: 'inline-flex' } })
group('inset', { x: positionRule('left', 'right'), y: positionRule('bottom', 'top') })
group('isolation', values('isolation', { isolate: 'isolate', auto: 'auto' }))
group('items', values('alignItems', itemValues))
group('justify', { ...values('justifyContent', contentValues), items: scopedRule('justifyItems', {}), self: scopedRule('justifySelf', {}) })
group('justifyItems', values('justifyItems', { center: 'center', end: 'end', normal: 'normal', 'safe center': 'safe center', 'safe end': 'safe end', start: 'start', stretch: 'stretch' }))
group('justifySelf', values('justifySelf', { auto: 'auto', center: 'center', end: 'end', 'safe center': 'safe center', 'safe end': 'safe end', start: 'start', stretch: 'stretch' }))
// prettier-ignore
group('line', { clamp: scopedRule('lineClamp', numericRule((key) => ({ overflow: 'hidden', display: '-webkit-box', WebkitBoxOrient: 'vertical', WebkitLineClamp: Number(key) }))) })
group('lineClamp', { none: { overflow: 'visible', display: 'block', WebkitBoxOrient: 'horizontal', WebkitLineClamp: 'none' } })
group('list', { ...values('listStylePosition', { inside: 'inside', outside: 'outside' }), ...values('listStyleType', { disc: 'disc', decimal: 'decimal', none: 'none' }), image: scopedRule('listImage', propertyRule('listStyleImage')) })
group('listImage', { none: { listStyleImage: 'none' } })
group('mask', { add: { maskComposite: 'add' }, alpha: { maskMode: 'alpha' }, auto: { maskSize: 'auto' }, clip: scopedRule('maskClip', {}), contain: { maskSize: 'contain' }, cover: { maskSize: 'cover' }, exclude: { maskComposite: 'exclude' }, intersect: { maskComposite: 'intersect' }, luminance: { maskMode: 'luminance' }, 'match-source': { maskMode: 'match-source' }, none: { maskImage: 'none' }, origin: scopedRule('maskOrigin', {}), position: scopedRule('maskPosition', propertyRule('maskPosition')), radial: scopedRule('maskRadial', scaleRule('maskImage')), repeat: scopedRule('maskRepeat', {}), size: scopedRule('maskSize', scaleRule('maskSize')), subtract: { maskComposite: 'subtract' } })
group('maskClip', values('maskClip', { 'border-box': 'border-box', 'padding-box': 'padding-box', 'content-box': 'content-box', 'fill-box': 'fill-box', 'stroke-box': 'stroke-box', 'view-box': 'view-box', 'no-clip': 'no-clip' }))
group('maskOrigin', values('maskOrigin', { 'border-box': 'border-box', 'padding-box': 'padding-box', 'content-box': 'content-box', 'fill-box': 'fill-box', 'stroke-box': 'stroke-box', 'view-box': 'view-box' }))
group('maskPosition', values('maskPosition', positionValues))
group('maskRepeat', values('maskRepeat', repeatValues))
group('max', { h: lengthRule('maxHeight'), size: scopedRule('maxSize', sizePropsRule('maxHeight', 'maxWidth')), w: lengthRule('maxWidth') })
group('min', { h: lengthRule('minHeight'), size: scopedRule('minSize', sizePropsRule('minHeight', 'minWidth')), w: lengthRule('minWidth') })
group('mix', { blend: scopedRule('mixBlend', {}) })
group('mixBlend', values('mixBlendMode', blendValues))
group('not', { sr: scopedRule('notSr', {}) })
group('notSr', { only: { position: 'static', width: 'auto', height: 'auto', padding: '0', margin: '0', overflow: 'visible', clip: 'auto', whiteSpace: 'normal' } })
group('object', { ...values('objectFit', { contain: 'contain', cover: 'cover', fill: 'fill', none: 'none', 'scale-down': 'scale-down' }), ...values('objectPosition', positionValues) })
group('origin', { center: { transformOrigin: 'center' }, top: scopedRule('originTop', { transformOrigin: 'top' }), right: { transformOrigin: 'right' }, bottom: scopedRule('originBottom', { transformOrigin: 'bottom' }), left: { transformOrigin: 'left' } })
group('originTop', { right: { transformOrigin: 'top right' }, left: { transformOrigin: 'top left' } })
group('originBottom', { right: { transformOrigin: 'bottom right' }, left: { transformOrigin: 'bottom left' } })
// prettier-ignore
group('outline', { ...values('outlineStyle', { solid: 'solid', dashed: 'dashed', dotted: 'dotted', double: 'double', none: 'none', hidden: 'hidden' }), offset: scopedRule('outlineOffset', propertyRule('outlineOffset', (key) => `${Number(key)}px`)) })
group('overflow', { ...values('overflow', { auto: 'auto', hidden: 'hidden', clip: 'clip', visible: 'visible', scroll: 'scroll' }), x: scopedRule('overflowX', {}), y: scopedRule('overflowY', {}) })
group('overflowX', values('overflowX', { auto: 'auto', hidden: 'hidden', clip: 'clip', visible: 'visible', scroll: 'scroll' }))
group('overflowY', values('overflowY', { auto: 'auto', hidden: 'hidden', clip: 'clip', visible: 'visible', scroll: 'scroll' }))
group('overscroll', { ...values('overscrollBehavior', { auto: 'auto', contain: 'contain', none: 'none' }), x: scopedRule('overscrollX', {}), y: scopedRule('overscrollY', {}) })
group('overscrollX', values('overscrollBehaviorX', { auto: 'auto', contain: 'contain', none: 'none' }))
group('overscrollY', values('overscrollBehaviorY', { auto: 'auto', contain: 'contain', none: 'none' }))
group('perspective', { ...values('perspective', { dramatic: '100px', near: '300px', normal: '500px', midrange: '800px', distant: '1200px', none: 'none' }), origin: scopedRule('perspectiveOrigin', {}) })
group('perspectiveOrigin', { center: { perspectiveOrigin: 'center' }, top: scopedRule('perspectiveTop', { perspectiveOrigin: 'top' }), right: { perspectiveOrigin: 'right' }, bottom: scopedRule('perspectiveBottom', { perspectiveOrigin: 'bottom' }), left: { perspectiveOrigin: 'left' } })
group('perspectiveTop', { right: { perspectiveOrigin: 'top right' }, left: { perspectiveOrigin: 'top left' } })
group('perspectiveBottom', { right: { perspectiveOrigin: 'bottom right' }, left: { perspectiveOrigin: 'bottom left' } })
group('place', { content: scopedRule('placeContent', {}), items: scopedRule('placeItems', {}), self: scopedRule('placeSelf', {}) })
group('placeContent', values('placeContent', contentValues))
group('placeItems', values('placeItems', { baseline: 'baseline', center: 'center', end: 'end', 'safe center': 'safe center', 'safe end': 'safe end', start: 'start', stretch: 'stretch' }))
group('placeSelf', values('placeSelf', { auto: 'auto', center: 'center', end: 'end', 'safe center': 'safe center', 'safe end': 'safe end', start: 'start', stretch: 'stretch' }))
group('pointer', { events: scopedRule('pointerEvents', {}) })
group('pointerEvents', values('pointerEvents', { auto: 'auto', none: 'none' }))
group('position', values('position', { static: 'static', fixed: 'fixed', absolute: 'absolute', relative: 'relative', sticky: 'sticky' }))
group('resize', values('resize', { none: 'none', y: 'vertical', x: 'horizontal' }))
group('rounded', { b: roundedRule('borderBottomLeftRadius', 'borderBottomRightRadius'), bl: roundedRule('borderBottomLeftRadius'), br: roundedRule('borderBottomRightRadius'), e: roundedRule('borderStartEndRadius', 'borderEndEndRadius'), ee: roundedRule('borderEndEndRadius'), es: roundedRule('borderEndStartRadius'), l: roundedRule('borderBottomLeftRadius', 'borderTopLeftRadius'), r: roundedRule('borderBottomRightRadius', 'borderTopRightRadius'), s: roundedRule('borderStartStartRadius', 'borderEndStartRadius'), se: roundedRule('borderStartEndRadius'), ss: roundedRule('borderStartStartRadius'), t: roundedRule('borderTopLeftRadius', 'borderTopRightRadius'), tl: roundedRule('borderTopLeftRadius'), tr: roundedRule('borderTopRightRadius') })
group('row', { auto: { gridRow: 'auto' }, end: scopedRule('rowEnd', propertyRule('gridRowEnd')), full: { gridRow: '1 / -1' }, span: numericRule((key) => ({ gridRow: `span ${key} / span ${key}` })), start: scopedRule('rowStart', propertyRule('gridRowStart')) })
group('rows', { none: { gridTemplateRows: 'none' }, subgrid: { gridTemplateRows: 'subgrid' } })
group('scheme', { normal: { colorScheme: 'normal' }, dark: { colorScheme: 'dark' }, light: scopedRule('schemeLight', { colorScheme: 'light' }), only: scopedRule('schemeOnly', {}) })
group('schemeLight', { dark: { colorScheme: 'light dark' } })
group('schemeOnly', { dark: { colorScheme: 'only dark' }, light: { colorScheme: 'only light' } })
group('scroll', values('scrollBehavior', { auto: 'auto', smooth: 'smooth' }))
group('scrollbar', { auto: { scrollbarWidth: 'auto' }, none: { scrollbarWidth: 'none' }, thin: { scrollbarWidth: 'thin' }, gutter: scopedRule('scrollbarGutter', {}), thumb: scopedRule('scrollbarThumb', colorRule('scrollbarColor')), track: scopedRule('scrollbarTrack', colorRule('scrollbarColor')) })
group('scrollbarGutter', { auto: { scrollbarGutter: 'auto' }, stable: { scrollbarGutter: 'stable' }, both: { scrollbarGutter: 'stable both-edges' } })
group('select', values('userSelect', { none: 'none', text: 'text', all: 'all', auto: 'auto' }))
group('self', values('alignSelf', itemValues))
group('shadow', { none: { boxShadow: 'none' }, lg: { boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1)' } })
group('size', { auto: { width: 'auto', height: 'auto' }, px: { width: '1px', height: '1px' } })
group('snap', { align: scopedRule('snapAlign', {}), always: { scrollSnapStop: 'always' }, center: { scrollSnapAlign: 'center' }, end: { scrollSnapAlign: 'end' }, none: { scrollSnapType: 'none' }, normal: { scrollSnapStop: 'normal' }, start: { scrollSnapAlign: 'start' } })
group('snapAlign', { none: { scrollSnapAlign: 'none' } })
group('sr', { only: { position: 'absolute', width: '1px', height: '1px', padding: '0', margin: '-1px', overflow: 'hidden', clip: 'rect(0, 0, 0, 0)', clipPath: 'inset(50%)', whiteSpace: 'nowrap', borderWidth: '0' } })
group('table', values('tableLayout', { auto: 'auto', fixed: 'fixed' }))
group('text', { ...values('textAlign', { center: 'center', left: 'left', right: 'right', justify: 'justify', start: 'start', end: 'end' }), ...values('textWrap', { wrap: 'wrap', nowrap: 'nowrap', balance: 'balance', pretty: 'pretty' }), base: { fontSize: '16px', lineHeight: '24px' }, clip: { textOverflow: 'clip' }, ellipsis: { textOverflow: 'ellipsis' }, lg: { fontSize: '18px', lineHeight: '28px' }, shadow: scopedRule('textShadow', propertyRule('textShadow')), sm: { fontSize: '14px', lineHeight: '20px' }, xl: { fontSize: '20px', lineHeight: '28px' }, xs: { fontSize: '12px', lineHeight: '16px' } })
group('touch', { ...values('touchAction', { auto: 'auto', none: 'none', manipulation: 'manipulation' }), pan: scopedRule('touchPan', {}), pinch: scopedRule('touchPinch', {}) })
group('touchPan', values('touchAction', { x: 'pan-x', left: 'pan-left', right: 'pan-right', y: 'pan-y', up: 'pan-up', down: 'pan-down' }))
group('touchPinch', { zoom: { touchAction: 'pinch-zoom' } })
group('tracking', { ...values('letterSpacing', { tighter: '-0.05em', tight: '-0.025em', normal: '0em', wide: '0.025em', wider: '0.05em', widest: '0.1em' }) })
group('transform', { none: { transform: 'none' }, '3d': { transformStyle: 'preserve-3d' }, flat: { transformStyle: 'flat' } })
group('transition', { ...values('transitionProperty', { all: 'all', opacity: 'opacity', shadow: 'box-shadow', transform: 'transform', none: 'none' }), normal: { transitionBehavior: 'normal' }, discrete: { transitionBehavior: 'allow-discrete' } })
// prettier-ignore
group('underline', { offset: scopedRule('underlineOffset', propertyRule('textUnderlineOffset', (key) => `${Number(key)}px`)) })
group('underlineOffset', { auto: { textUnderlineOffset: 'auto' } })
group('visibility', values('visibility', { visible: 'visible', hidden: 'hidden', collapse: 'collapse' }))
group('whitespace', values('whiteSpace', { normal: 'normal', nowrap: 'nowrap', pre: 'pre', 'pre-line': 'pre-line', 'pre-wrap': 'pre-wrap', 'break-spaces': 'break-spaces' }))
group('will', { change: scopedRule('willChange', propertyRule('willChange')) })
group('willChange', values('willChange', { auto: 'auto', scroll: 'scroll-position', contents: 'contents', transform: 'transform' }))
group('wrap', values('overflowWrap', { 'break-word': 'break-word', anywhere: 'anywhere', normal: 'normal' }))
export const absolute: U['absolute'] = u<U['absolute']>('absolute', { position: 'absolute' })
export const accent: U['accent'] = u<U['accent']>('accent', colorRule('accentColor'))
export const active: U['active'] = u<U['active']>('active', variantRule(':active'))
export const after: U['after'] = u<U['after']>('after', variantRule('::after'))
export const align: U['align'] = u<U['align']>('align', propertyRule('verticalAlign'))
export const animate: U['animate'] = u<U['animate']>('animate', propertyRule('animation'))
export const antialiased: U['antialiased'] = u<U['antialiased']>('antialiased', { WebkitFontSmoothing: 'antialiased', MozOsxFontSmoothing: 'grayscale' })
export const appearance: U['appearance'] = u<U['appearance']>('appearance', propertyRule('appearance'), 'appearance')
export const aria: U['aria'] = u<U['aria']>('aria', variantRule('[aria]'))
export const ariaChecked: U['ariaChecked'] = u<U['ariaChecked']>('ariaChecked', variantRule('[aria-checked=true]'))
export const ariaDisabled: U['ariaDisabled'] = u<U['ariaDisabled']>('ariaDisabled', variantRule('[aria-disabled=true]'))
export const ariaExpanded: U['ariaExpanded'] = u<U['ariaExpanded']>('ariaExpanded', variantRule('[aria-expanded=true]'))
export const ariaSelected: U['ariaSelected'] = u<U['ariaSelected']>('ariaSelected', variantRule('[aria-selected=true]'))
// prettier-ignore
export const aspect: U['aspect'] = u<U['aspect']>('aspect', propertyRule('aspectRatio', (key) => (Number.isFinite(Number(key)) ? `${Number(key) * 4} / 9` : key)), 'aspect')
group('aspect', { auto: { aspectRatio: 'auto' }, video: { aspectRatio: '16 / 9' } })
export const atLg: U['atLg'] = u<U['atLg']>('atLg', variantRule('container(width >= 1024px)'))
export const atMd: U['atMd'] = u<U['atMd']>('atMd', variantRule('container(width >= 768px)'))
export const atSm: U['atSm'] = u<U['atSm']>('atSm', variantRule('container(width >= 640px)'))
export const auto: U['auto'] = u<U['auto']>('auto', {}, 'auto')
export const autofill: U['autofill'] = u<U['autofill']>('autofill', variantRule(':autofill'))
export const backdrop: U['backdrop'] = u<U['backdrop']>('backdrop', {}, 'backdrop')
export const backface: U['backface'] = u<U['backface']>('backface', {}, 'backface')
group('backdrop', { filter: scopedRule('backdropFilter', propertyRule('backdropFilter')), blur: scopedRule('backdropFilter', filterRule('backdropFilter', 'blur', 'px')), brightness: scopedRule('backdropFilter', filterRule('backdropFilter', 'brightness')), contrast: scopedRule('backdropFilter', filterRule('backdropFilter', 'contrast')), grayscale: scopedRule('backdropFilter', defaultFilterRule('backdropFilter', 'grayscale', '100%')), hue: scopedRule('backdropHue', {}), invert: scopedRule('backdropFilter', defaultFilterRule('backdropFilter', 'invert', '100%')), opacity: scopedRule('backdropFilter', filterRule('backdropFilter', 'opacity')), saturate: scopedRule('backdropFilter', filterRule('backdropFilter', 'saturate')), sepia: scopedRule('backdropFilter', defaultFilterRule('backdropFilter', 'sepia', '100%')) })
group('backdropHue', { rotate: scopedRule('backdropFilter', filterRule('backdropFilter', 'hue-rotate', 'deg')) })
group('backface', values('backfaceVisibility', { hidden: 'hidden', visible: 'visible' }))
export const basis: U['basis'] = u<U['basis']>('basis', lengthRule('flexBasis'))
export const before: U['before'] = u<U['before']>('before', variantRule('::before'))
export const bg: U['bg'] = u<U['bg']>('bg', colorRule('background'), 'bg')
export const block: U['block'] = u<U['block']>('block', { display: 'block' })
export const blur: U['blur'] = u<U['blur']>('blur', filterRule('filter', 'blur', 'px'))
export const border: U['border'] = u<U['border']>('border', borderRule)
export const bottom: U['bottom'] = u<U['bottom']>('bottom', positionRule('bottom'))
export const box: U['box'] = u<U['box']>('box', {}, 'box')
export const break_: U['break'] = u<U['break']>('break', {}, 'break')
export { break_ as break }
export const brightness: U['brightness'] = u<U['brightness']>('brightness', filterRule('filter', 'brightness'))
export const caption: U['caption'] = u<U['caption']>('caption', {}, 'caption')
export const capitalize: U['capitalize'] = u<U['capitalize']>('capitalize', { textTransform: 'capitalize' })
export const caret: U['caret'] = u<U['caret']>('caret', colorRule('caretColor'))
export const checked: U['checked'] = u<U['checked']>('checked', variantRule(':checked'))
export const child: U['child'] = u<U['child']>('child', variantRule('> *'))
export const clear: U['clear'] = u<U['clear']>('clear', {}, 'clear')
export const col: U['col'] = u<U['col']>('col', columnRule, 'col')
export const columns: U['columns'] = u<U['columns']>('columns', propertyRule('columns'), 'columns')
group('columns', { auto: { columns: 'auto' } })
export const color: U['color'] = u<U['color']>('color', colorRule('color'))
export const cols: U['cols'] = u<U['cols']>('cols', scopedRule('cols', columnsRule))
export const colStart: U['colStart'] = u<U['colStart']>('colStart', propertyRule('gridColumnStart'))
export const container: U['container'] = u<U['container']>('container', { width: '100%' })
export const content: U['content'] = u<U['content']>('content', propertyRule('content'), 'content')
export const contrast: U['contrast'] = u<U['contrast']>('contrast', filterRule('filter', 'contrast'))
export const contrastLess: U['contrastLess'] = u<U['contrastLess']>('contrastLess', variantRule('media(prefers-contrast: less)'))
export const contrastMore: U['contrastMore'] = u<U['contrastMore']>('contrastMore', variantRule('media(prefers-contrast: more)'))
export const css: U['css'] = u<U['css']>('css', splitRule)
export const cursor: U['cursor'] = u<U['cursor']>('cursor', propertyRule('cursor'), 'cursor')
export const dark: U['dark'] = u<U['dark']>('dark', darkRule)
export const data: U['data'] = u<U['data']>('data', variantRule('[data]'))
export const dataActive: U['dataActive'] = u<U['dataActive']>('dataActive', variantRule('[data-active]'))
export const decoration: U['decoration'] = u<U['decoration']>('decoration', colorRule('textDecorationColor'), 'decoration')
// prettier-ignore
export const delay: U['delay'] = u<U['delay']>('delay', numericRule((key) => ({ transitionDelay: `${key}ms` })))
export const descendant: U['descendant'] = u<U['descendant']>('descendant', variantRule(' *'))
export const disabled: U['disabled'] = u<U['disabled']>('disabled', variantRule(':disabled'))
export const display: U['display'] = u<U['display']>('display', propertyRule('display'), 'display')
export const divide: U['divide'] = u<U['divide']>('divide', colorRule('borderColor'), 'divide')
// prettier-ignore
export const duration: U['duration'] = u<U['duration']>('duration', numericRule((key) => ({ transitionDuration: `${key}ms` })), 'duration')
group('duration', { initial: { transitionDuration: 'initial' } })
export const ease: U['ease'] = u<U['ease']>('ease', propertyRule('transitionTimingFunction'), 'ease')
group('ease', { linear: { transitionTimingFunction: 'linear' }, in: { transitionTimingFunction: 'cubic-bezier(0.4, 0, 1, 1)' }, out: { transitionTimingFunction: 'cubic-bezier(0, 0, 0.2, 1)' }, initial: { transitionTimingFunction: 'initial' } })
group('ease', { in: scopedRule('easeIn', { transitionTimingFunction: 'cubic-bezier(0.4, 0, 1, 1)' }) })
group('easeIn', { out: { transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)' } })
export const empty: U['empty'] = u<U['empty']>('empty', variantRule(':empty'))
export const enabled: U['enabled'] = u<U['enabled']>('enabled', variantRule(':enabled'))
export const end: U['end'] = u<U['end']>('end', positionRule('insetInlineEnd'))
export const even: U['even'] = u<U['even']>('even', variantRule(':nth-child(even)'))
export const field: U['field'] = u<U['field']>('field', {}, 'field')
export const file: U['file'] = u<U['file']>('file', variantRule('::file-selector-button'))
export const fill: U['fill'] = u<U['fill']>('fill', colorRule('fill'))
export const filter: U['filter'] = u<U['filter']>('filter', propertyRule('filter'), 'filter')
export const first: U['first'] = u<U['first']>('first', variantRule(':first-child'))
export const firstLetter: U['firstLetter'] = u<U['firstLetter']>('firstLetter', variantRule('::first-letter'))
export const firstLine: U['firstLine'] = u<U['firstLine']>('firstLine', variantRule('::first-line'))
export const firstOfType: U['firstOfType'] = u<U['firstOfType']>('firstOfType', variantRule(':first-of-type'))
export const fixed: U['fixed'] = u<U['fixed']>('fixed', { position: 'fixed' })
export const flex: U['flex'] = u<U['flex']>('flex', flexRule)
export const float: U['float'] = u<U['float']>('float', {}, 'float')
group('float', values('float', { right: 'right', left: 'left', 'inline-start': 'inline-start', 'inline-end': 'inline-end', none: 'none' }))
export const flow: U['flow'] = u<U['flow']>('flow', {}, 'flow')
export const focus: U['focus'] = u<U['focus']>('focus', variantRule(':focus'))
export const focusVisible: U['focusVisible'] = u<U['focusVisible']>('focusVisible', variantRule(':focus-visible'))
export const focusWithin: U['focusWithin'] = u<U['focusWithin']>('focusWithin', variantRule(':focus-within'))
// prettier-ignore
export const font: U['font'] = u<U['font']>('font', scopedRule('font', numericRule((key) => ({ fontWeight: Number(key) }))))
export const forcedColorAdjust: U['forcedColorAdjust'] = u<U['forcedColorAdjust']>('forcedColorAdjust', {}, 'forcedColorAdjust')
group('forcedColorAdjust', values('forcedColorAdjust', { auto: 'auto', none: 'none' }))
export const forcedColors: U['forcedColors'] = u<U['forcedColors']>('forcedColors', variantRule('media(forced-colors: active)'))
export const from: U['from'] = u<U['from']>('from', colorRule('--tw-gradient-from'))
export const gap: U['gap'] = u<U['gap']>('gap', scopedRule('gap', scaleRule('gap')))
export const grayscale: U['grayscale'] = u<U['grayscale']>('grayscale', defaultFilterRule('filter', 'grayscale', '100%'))
export const grid: U['grid'] = u<U['grid']>('grid', { display: 'grid' }, 'grid')
export const group_: U['group'] = u<U['group']>('group', variantRule('.group &'))
export { group_ as group }
export const groupFocus: U['groupFocus'] = u<U['groupFocus']>('groupFocus', variantRule('.group:focus &'))
export const groupHover: U['groupHover'] = u<U['groupHover']>('groupHover', variantRule('.group:hover &'))
export const grow: U['grow'] = u<U['grow']>('grow', propertyRule('flexGrow'))
export const h: U['h'] = u<U['h']>('h', lengthRule('height', '100vh'))
export const has: U['has'] = u<U['has']>('has', variantRule(':has(*)'))
export const height: U['height'] = u<U['height']>('height', lengthRule('height', '100vh'))
export const hidden: U['hidden'] = u<U['hidden']>('hidden', { display: 'none' })
export const hover: U['hover'] = u<U['hover']>('hover', variantRule(':hover'))
export const hue: U['hue'] = u<U['hue']>('hue', {}, 'hue')
group('hue', { rotate: scopedRule('filter', filterRule('filter', 'hue-rotate', 'deg')) })
export const hyphens: U['hyphens'] = u<U['hyphens']>('hyphens', {}, 'hyphens')
export const indeterminate: U['indeterminate'] = u<U['indeterminate']>('indeterminate', variantRule(':indeterminate'))
export const indent: U['indent'] = u<U['indent']>('indent', lengthRule('textIndent'))
export const inline: U['inline'] = u<U['inline']>('inline', { display: 'inline' }, 'inline')
export const inlineBlock: U['inlineBlock'] = u<U['inlineBlock']>('inlineBlock', { display: 'inline-block' })
export const inlineFlex: U['inlineFlex'] = u<U['inlineFlex']>('inlineFlex', { display: 'inline-flex' })
export const inset: U['inset'] = u<U['inset']>('inset', positionRule('inset'), 'inset')
export const invalid: U['invalid'] = u<U['invalid']>('invalid', variantRule(':invalid'))
export const invert: U['invert'] = u<U['invert']>('invert', defaultFilterRule('filter', 'invert', '100%'))
export const isolation: U['isolation'] = u<U['isolation']>('isolation', {}, 'isolation')
export const italic: U['italic'] = u<U['italic']>('italic', { fontStyle: 'italic' })
export const items: U['items'] = u<U['items']>('items', {}, 'items')
export const justify: U['justify'] = u<U['justify']>('justify', {}, 'justify')
export const landscape: U['landscape'] = u<U['landscape']>('landscape', variantRule('media(orientation: landscape)'))
export const last: U['last'] = u<U['last']>('last', variantRule(':last-child'))
export const lastOfType: U['lastOfType'] = u<U['lastOfType']>('lastOfType', variantRule(':last-of-type'))
export const leading: U['leading'] = u<U['leading']>('leading', scaleRule('lineHeight'))
export const left: U['left'] = u<U['left']>('left', positionRule('left'))
export const lg: U['lg'] = u<U['lg']>('lg', mediaRule('1024px'))
export const light: U['light'] = u<U['light']>('light', variantRule('.light &'))
export const line: U['line'] = u<U['line']>('line', {}, 'line')
export const lineThrough: U['lineThrough'] = u<U['lineThrough']>('lineThrough', { textDecorationLine: 'line-through' })
export const liningNums: U['liningNums'] = u<U['liningNums']>('liningNums', { fontVariantNumeric: 'lining-nums' })
export const list: U['list'] = u<U['list']>('list', propertyRule('listStyleType'), 'list')
export const lowercase: U['lowercase'] = u<U['lowercase']>('lowercase', { textTransform: 'lowercase' })
export const ltr: U['ltr'] = u<U['ltr']>('ltr', variantRule('[dir=ltr] &'))
export const m: U['m'] = u<U['m']>('m', spacingRule('margin'))
export const margin: U['margin'] = u<U['margin']>('margin', spacingRule('margin'))
export const marker: U['marker'] = u<U['marker']>('marker', variantRule('::marker'))
export const mask: U['mask'] = u<U['mask']>('mask', propertyRule('maskImage'), 'mask')
export const max: U['max'] = u<U['max']>('max', {}, 'max')
export const maxMd: U['maxMd'] = u<U['maxMd']>('maxMd', variantRule('media(width < 768px)'))
export const maxSm: U['maxSm'] = u<U['maxSm']>('maxSm', variantRule('media(width < 640px)'))
export const mb: U['mb'] = u<U['mb']>('mb', spacingRule('marginBottom'))
export const md: U['md'] = u<U['md']>('md', mediaRule('768px'))
export const me: U['me'] = u<U['me']>('me', spacingRule('marginInlineEnd'))
export const min: U['min'] = u<U['min']>('min', {}, 'min')
export const mix: U['mix'] = u<U['mix']>('mix', {}, 'mix')
export const ml: U['ml'] = u<U['ml']>('ml', spacingRule('marginLeft'))
export const motionReduce: U['motionReduce'] = u<U['motionReduce']>('motionReduce', variantRule('media(prefers-reduced-motion: reduce)'))
export const motionSafe: U['motionSafe'] = u<U['motionSafe']>('motionSafe', variantRule('media(prefers-reduced-motion: no-preference)'))
export const mr: U['mr'] = u<U['mr']>('mr', spacingRule('marginRight'))
export const ms: U['ms'] = u<U['ms']>('ms', spacingRule('marginInlineStart'))
export const mt: U['mt'] = u<U['mt']>('mt', spacingRule('marginTop'))
export const mx: U['mx'] = u<U['mx']>('mx', scopedRule('mx', spacingRule('marginLeft', 'marginRight')))
group('mx', { auto: { marginLeft: 'auto', marginRight: 'auto' } })
export const my: U['my'] = u<U['my']>('my', scopedRule('my', spacingRule('marginBottom', 'marginTop')))
group('my', { auto: { marginBottom: 'auto', marginTop: 'auto' } })
export const none: U['none'] = u<U['none']>('none', { textDecorationLine: 'none' })
export const normal: U['normal'] = u<U['normal']>('normal', { fontStyle: 'normal' })
export const not: U['not'] = u<U['not']>('not', {}, 'not')
export const notSr: U['notSr'] = u<U['notSr']>('notSr', {}, 'notSr')
export const object: U['object'] = u<U['object']>('object', propertyRule('objectPosition'), 'object')
export const odd: U['odd'] = u<U['odd']>('odd', variantRule(':nth-child(odd)'))
export const oldstyleNums: U['oldstyleNums'] = u<U['oldstyleNums']>('oldstyleNums', { fontVariantNumeric: 'oldstyle-nums' })
export const only: U['only'] = u<U['only']>('only', variantRule(':only-child'))
export const onlyOfType: U['onlyOfType'] = u<U['onlyOfType']>('onlyOfType', variantRule(':only-of-type'))
export const opacity: U['opacity'] = u<U['opacity']>('opacity', opacityRule('opacity'))
export const optional: U['optional'] = u<U['optional']>('optional', variantRule(':optional'))
export const order: U['order'] = u<U['order']>('order', propertyRule('order'))
export const ordinal: U['ordinal'] = u<U['ordinal']>('ordinal', { fontVariantNumeric: 'ordinal' })
export const origin: U['origin'] = u<U['origin']>('origin', propertyRule('transformOrigin'), 'origin')
export const outline: U['outline'] = u<U['outline']>('outline', outlineRule)
export const overline: U['overline'] = u<U['overline']>('overline', { textDecorationLine: 'overline' })
export const overflow: U['overflow'] = u<U['overflow']>('overflow', {}, 'overflow')
export const overscroll: U['overscroll'] = u<U['overscroll']>('overscroll', {}, 'overscroll')
export const p: U['p'] = u<U['p']>('p', spacingRule('padding'))
export const padding: U['padding'] = u<U['padding']>('padding', spacingRule('padding'))
export const pb: U['pb'] = u<U['pb']>('pb', spacingRule('paddingBottom'))
export const pe: U['pe'] = u<U['pe']>('pe', spacingRule('paddingInlineEnd'))
export const peer: U['peer'] = u<U['peer']>('peer', variantRule('.peer ~ &'))
export const peerFocus: U['peerFocus'] = u<U['peerFocus']>('peerFocus', variantRule('.peer:focus ~ &'))
export const peerHover: U['peerHover'] = u<U['peerHover']>('peerHover', variantRule('.peer:hover ~ &'))
export const perspective: U['perspective'] = u<U['perspective']>('perspective', propertyRule('perspective'), 'perspective')
export const placeholder: U['placeholder'] = u<U['placeholder']>('placeholder', variantRule('::placeholder'))
export const placeholderShown: U['placeholderShown'] = u<U['placeholderShown']>('placeholderShown', variantRule(':placeholder-shown'))
export const place: U['place'] = u<U['place']>('place', {}, 'place')
export const pl: U['pl'] = u<U['pl']>('pl', spacingRule('paddingLeft'))
export const pointer: U['pointer'] = u<U['pointer']>('pointer', {}, 'pointer')
export const pointerCoarse: U['pointerCoarse'] = u<U['pointerCoarse']>('pointerCoarse', variantRule('media(pointer: coarse)'))
export const pointerFine: U['pointerFine'] = u<U['pointerFine']>('pointerFine', variantRule('media(pointer: fine)'))
export const portrait: U['portrait'] = u<U['portrait']>('portrait', variantRule('media(orientation: portrait)'))
export const position: U['position'] = u<U['position']>('position', {}, 'position')
export const pr: U['pr'] = u<U['pr']>('pr', spacingRule('paddingRight'))
export const prefersDark: U['prefersDark'] = u<U['prefersDark']>('prefersDark', variantRule('media(prefers-color-scheme: dark)'))
export const print: U['print'] = u<U['print']>('print', variantRule('media(print)'))
export const proportionalNums: U['proportionalNums'] = u<U['proportionalNums']>('proportionalNums', { fontVariantNumeric: 'proportional-nums' })
export const ps: U['ps'] = u<U['ps']>('ps', spacingRule('paddingInlineStart'))
export const pt: U['pt'] = u<U['pt']>('pt', spacingRule('paddingTop'))
export const px: U['px'] = u<U['px']>('px', spacingRule('paddingLeft', 'paddingRight'))
export const py: U['py'] = u<U['py']>('py', spacingRule('paddingBottom', 'paddingTop'))
export const readOnly: U['readOnly'] = u<U['readOnly']>('readOnly', variantRule(':read-only'))
export const relative: U['relative'] = u<U['relative']>('relative', { position: 'relative' })
export const required: U['required'] = u<U['required']>('required', variantRule(':required'))
export const resize: U['resize'] = u<U['resize']>('resize', { resize: 'both' }, 'resize')
export const right: U['right'] = u<U['right']>('right', positionRule('right'))
export const rotate: U['rotate'] = u<U['rotate']>('rotate', transformRule('rotate', 'deg'))
export const rounded: U['rounded'] = u<U['rounded']>('rounded', roundedRule(), 'rounded')
export const row: U['row'] = u<U['row']>('row', rowRule, 'row')
export const rows: U['rows'] = u<U['rows']>('rows', scopedRule('rows', rowsRule))
export const rtl: U['rtl'] = u<U['rtl']>('rtl', variantRule('[dir=rtl] &'))
export const saturate: U['saturate'] = u<U['saturate']>('saturate', filterRule('filter', 'saturate'))
export const scale: U['scale'] = u<U['scale']>('scale', transformRule('scale'))
export const scheme: U['scheme'] = u<U['scheme']>('scheme', {}, 'scheme')
export const scroll: U['scroll'] = u<U['scroll']>('scroll', {}, 'scroll')
export const scrollbar: U['scrollbar'] = u<U['scrollbar']>('scrollbar', {}, 'scrollbar')
export const select: U['select'] = u<U['select']>('select', {}, 'select')
export const selection: U['selection'] = u<U['selection']>('selection', variantRule('::selection'))
export const self: U['self'] = u<U['self']>('self', {}, 'self')
export const sepia: U['sepia'] = u<U['sepia']>('sepia', defaultFilterRule('filter', 'sepia', '100%'))
export const shadow: U['shadow'] = u<U['shadow']>('shadow', propertyRule('boxShadow'), 'shadow')
export const shrink: U['shrink'] = u<U['shrink']>('shrink', propertyRule('flexShrink'))
export const size: U['size'] = u<U['size']>('size', sizeRule, 'size')
export const skew: U['skew'] = u<U['skew']>('skew', transformRule('skew', 'deg'), 'skew')
group('skew', { x: transformRule('skewX', 'deg'), y: transformRule('skewY', 'deg') })
export const slashedZero: U['slashedZero'] = u<U['slashedZero']>('slashedZero', { fontVariantNumeric: 'slashed-zero' })
export const sm: U['sm'] = u<U['sm']>('sm', mediaRule('640px'))
export const snap: U['snap'] = u<U['snap']>('snap', {}, 'snap')
export const sr: U['sr'] = u<U['sr']>('sr', {}, 'sr')
export const stackedFractions: U['stackedFractions'] = u<U['stackedFractions']>('stackedFractions', { fontVariantNumeric: 'stacked-fractions' })
export const start: U['start'] = u<U['start']>('start', positionRule('insetInlineStart'))
export const static_: U['static'] = u<U['static']>('static', { position: 'static' })
export { static_ as static }
export const stroke: U['stroke'] = u<U['stroke']>('stroke', colorRule('stroke'))
export const subpixel: U['subpixel'] = u<U['subpixel']>('subpixel', {}, 'subpixel')
group('subpixel', { antialiased: { WebkitFontSmoothing: 'auto', MozOsxFontSmoothing: 'auto' } })
export const supports: U['supports'] = u<U['supports']>('supports', variantRule('@supports'))
export const table: U['table'] = u<U['table']>('table', { display: 'table' }, 'table')
// prettier-ignore
export const tab: U['tab'] = u<U['tab']>('tab', numericRule((key) => ({ tabSize: Number(key) })))
export const tabularNums: U['tabularNums'] = u<U['tabularNums']>('tabularNums', { fontVariantNumeric: 'tabular-nums' })
export const target: U['target'] = u<U['target']>('target', variantRule(':target'))
export const text: U['text'] = u<U['text']>('text', textRule)
export const to: U['to'] = u<U['to']>('to', colorRule('--tw-gradient-to'))
export const top: U['top'] = u<U['top']>('top', positionRule('top'))
export const touch: U['touch'] = u<U['touch']>('touch', {}, 'touch')
export const tracking: U['tracking'] = u<U['tracking']>('tracking', scaleRule('letterSpacing'), 'tracking')
export const transform: U['transform'] = u<U['transform']>('transform', propertyRule('transform'), 'transform')
export const transition: U['transition'] = u<U['transition']>('transition', propertyRule('transitionProperty'), 'transition')
export const translate: U['translate'] = u<U['translate']>('translate', propertyRule('transform'), 'translate')
group('translate', { full: { transform: 'translate(100%, 100%)' }, none: { transform: 'none' }, px: { transform: 'translate(1px, 1px)' }, x: translateRule('X'), y: translateRule('Y') })
export const truncate: U['truncate'] = u<U['truncate']>('truncate', { overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' })
export const underline: U['underline'] = u<U['underline']>('underline', { textDecorationLine: 'underline' }, 'underline')
export const uppercase: U['uppercase'] = u<U['uppercase']>('uppercase', { textTransform: 'uppercase' })
export const valid: U['valid'] = u<U['valid']>('valid', variantRule(':valid'))
export const visibility: U['visibility'] = u<U['visibility']>('visibility', {}, 'visibility')
export const visited: U['visited'] = u<U['visited']>('visited', variantRule(':visited'))
export const w: U['w'] = u<U['w']>('w', lengthRule('width', '100vw'))
export const whitespace: U['whitespace'] = u<U['whitespace']>('whitespace', {}, 'whitespace')
export const width: U['width'] = u<U['width']>('width', lengthRule('width', '100vw'))
export const will: U['will'] = u<U['will']>('will', {}, 'will')
export const wrap: U['wrap'] = u<U['wrap']>('wrap', {}, 'wrap')
export const xl: U['xl'] = u<U['xl']>('xl', mediaRule('1280px'))
export const xl2: U['xl2'] = u<U['xl2']>('xl2', mediaRule('1536px'))
export const z: U['z'] = u<U['z']>('z', propertyRule('zIndex'), 'z')
group('z', { auto: { zIndex: 'auto' } })
export const zoom: U['zoom'] = u<U['zoom']>('zoom', propertyRule('zoom'))
export const define = <T = C>(name: string, css: RuntimeStyle, scopeName?: string): T => u<T>(name, css, scopeName)
