import { borderRule, borderSideRule, colorRule, columnRule, columnsRule, darkRule, flexRule, group, lengthRule, mediaRule, numericRule, positionRule, roundedRule, scaleRule, scopedRule, sizeRule, splitRule, textRule, translateRule, utility, values } from './utils.ts'
import type { Chain, RuntimeStyle, Utility } from './types.ts'

group('auto', { cols: scaleRule('gridAutoColumns') })
group('content', values('alignContent', { center: 'center', end: 'flex-end', start: 'flex-start', stretch: 'stretch' }))
group('flex', { ...values('flexDirection', { col: 'column', row: 'row' }), ...values('flexWrap', { nowrap: 'nowrap', wrap: 'wrap' }) })
group('flow', values('gridAutoFlow', { col: 'column', row: 'row' }))
group('font', values('fontWeight', { bold: 700, medium: 500, normal: 400, semibold: 600 }))
group('font', { sans: { fontFamily: 'Arial, Helvetica, sans-serif' } })
group('gap', { x: scaleRule('columnGap'), y: scaleRule('rowGap') })
group('inline', { block: { display: 'inline-block' }, flex: { display: 'inline-flex' } })
group('items', values('alignItems', { center: 'center', end: 'flex-end', start: 'flex-start', stretch: 'stretch' }))
group('justify', { ...values('justifyContent', { between: 'space-between', center: 'center', end: 'flex-end', start: 'flex-start' }), items: scopedRule('justifyItems', {}) })
group('justifyItems', values('justifyItems', { center: 'center', end: 'end', start: 'start', stretch: 'stretch' }))
group('max', { h: lengthRule('maxHeight'), w: lengthRule('maxWidth') })
group('min', { h: lengthRule('minHeight'), w: lengthRule('minWidth') })
group('mx', { auto: { marginLeft: 'auto', marginRight: 'auto' } })
group('my', { auto: { marginBottom: 'auto', marginTop: 'auto' } })
group('overflow', values('overflow', { auto: 'auto', hidden: 'hidden', scroll: 'scroll', visible: 'visible' }))
group('place', { items: scopedRule('placeItems', {}) })
group('placeItems', values('placeItems', { center: 'center', end: 'end', start: 'start', stretch: 'stretch' }))
group('pointer', { events: scopedRule('pointerEvents', {}) })
group('pointerEvents', values('pointerEvents', { auto: 'auto', none: 'none' }))
group('table', values('tableLayout', { auto: 'auto', fixed: 'fixed' }))
group('text', { base: { fontSize: '16px', lineHeight: '24px' }, sm: { fontSize: '14px', lineHeight: '20px' }, xs: { fontSize: '12px', lineHeight: '16px' }, ...values('textAlign', { center: 'center', left: 'left', right: 'right' }) })
group('tracking', { tight: { letterSpacing: '-0.025em' } })
group('border', { b: borderSideRule('borderBottom'), collapse: { borderCollapse: 'collapse' }, l: borderSideRule('borderLeft'), r: borderSideRule('borderRight'), t: borderSideRule('borderTop'), x: borderSideRule('borderLeft', 'borderRight'), y: borderSideRule('borderBottom', 'borderTop') })
group('rounded', { full: { borderRadius: '9999px' } })
group('translate', { x: translateRule('X'), y: translateRule('Y') })
group('cols', { subgrid: { gridTemplateColumns: 'subgrid' } })
group('col', { full: { gridColumn: '1 / -1' }, span: columnRule })

export const absolute: Utility['absolute'] = utility('absolute', { position: 'absolute' })
export const auto: Utility['auto'] = utility('auto', {}, 'auto')
export const bg: Utility['bg'] = utility('bg', colorRule('background'))
export const block: Utility['block'] = utility('block', { display: 'block' })
export const border: Utility['border'] = utility('border', borderRule)
export const cols: Utility['cols'] = utility('cols', scopedRule('cols', columnsRule))
export const col: Utility['col'] = utility('col', scopedRule('col', columnRule))
export const colStart: Utility['colStart'] = utility('colStart', numericRule((key) => ({ gridColumnStart: Number(key) })))
export const content: Utility['content'] = utility('content', {}, 'content')
export const css: Utility['css'] = utility('css', splitRule)
export const dark: Utility['dark'] = utility('dark', darkRule)
export const flex: Utility['flex'] = utility('flex', flexRule)
export const flow: Utility['flow'] = utility('flow', {}, 'flow')
export const font: Utility['font'] = utility('font', scopedRule('font', numericRule((key) => ({ fontWeight: Number(key) }))))
export const gap: Utility['gap'] = utility('gap', scopedRule('gap', scaleRule('gap')))
export const grid: Utility['grid'] = utility('grid', { display: 'grid' })
export const h: Utility['h'] = utility('h', lengthRule('height'))
export const hidden: Utility['hidden'] = utility('hidden', { display: 'none' })
export const inline: Utility['inline'] = utility('inline', { display: 'inline' }, 'inline')
export const inlineBlock: Utility['inlineBlock'] = utility('inlineBlock', { display: 'inline-block' })
export const inlineFlex: Utility['inlineFlex'] = utility('inlineFlex', { display: 'inline-flex' })
export const inset: Utility['inset'] = utility('inset', positionRule('inset'))
export const items: Utility['items'] = utility('items', {}, 'items')
export const justify: Utility['justify'] = utility('justify', {}, 'justify')
export const leading: Utility['leading'] = utility('leading', scaleRule('lineHeight'))
export const left: Utility['left'] = utility('left', positionRule('left'))
export const m: Utility['m'] = utility('m', scaleRule('margin'))
export const max: Utility['max'] = utility('max', {}, 'max')
export const mb: Utility['mb'] = utility('mb', scaleRule('marginBottom'))
export const min: Utility['min'] = utility('min', {}, 'min')
export const ml: Utility['ml'] = utility('ml', scaleRule('marginLeft'))
export const mr: Utility['mr'] = utility('mr', scaleRule('marginRight'))
export const mt: Utility['mt'] = utility('mt', scaleRule('marginTop'))
export const mx: Utility['mx'] = utility('mx', scopedRule('mx', scaleRule('marginLeft', 'marginRight')))
export const my: Utility['my'] = utility('my', scopedRule('my', scaleRule('marginBottom', 'marginTop')))
export const overflow: Utility['overflow'] = utility('overflow', {}, 'overflow')
export const p: Utility['p'] = utility('p', scaleRule('padding'))
export const pb: Utility['pb'] = utility('pb', scaleRule('paddingBottom'))
export const pl: Utility['pl'] = utility('pl', scaleRule('paddingLeft'))
export const pr: Utility['pr'] = utility('pr', scaleRule('paddingRight'))
export const pt: Utility['pt'] = utility('pt', scaleRule('paddingTop'))
export const px: Utility['px'] = utility('px', scaleRule('paddingLeft', 'paddingRight'))
export const py: Utility['py'] = utility('py', scaleRule('paddingBottom', 'paddingTop'))
export const place: Utility['place'] = utility('place', {}, 'place')
export const pointer: Utility['pointer'] = utility('pointer', {}, 'pointer')
export const relative: Utility['relative'] = utility('relative', { position: 'relative' })
export const rounded: Utility['rounded'] = utility('rounded', roundedRule)
export const size: Utility['size'] = utility('size', sizeRule)
export const sm: Utility['sm'] = utility('sm', mediaRule('640px'))
export const table: Utility['table'] = utility('table', { display: 'table' }, 'table')
export const text: Utility['text'] = utility('text', textRule)
export const tracking: Utility['tracking'] = utility('tracking', {}, 'tracking')
export const top: Utility['top'] = utility('top', positionRule('top'))
export const translate: Utility['translate'] = utility('translate', {}, 'translate')
export const w: Utility['w'] = utility('w', lengthRule('width'))
export const md: Utility['md'] = utility('md', mediaRule('768px'))
export const define = <T = Chain>(name: string, css: RuntimeStyle, scopeName?: string): T => utility<T>(name, css, scopeName)
